package main

import (
	"context"
	"fmt"
	"log"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	beerAws "github.com/tristanbatchler/itsbeeroclock/backend/internal/aws"
	"github.com/tristanbatchler/itsbeeroclock/backend/internal/models"
)

type CatalogueItem struct {
	PK      string  `dynamodbav:"PK"`     // CATALOGUE
	SK      string  `dynamodbav:"SK"`     // BEER#{id}
	GSI1PK  string  `dynamodbav:"GSI1PK"` // CATALOGUE
	GSI1SK  string  `dynamodbav:"GSI1SK"` // {brewery}#{name}
	BeerID  string  `dynamodbav:"BeerID"`
	Name    string  `dynamodbav:"Name"`
	Brewery string  `dynamodbav:"Brewery"`
	ABV     float64 `dynamodbav:"ABV"`
	Image   string  `dynamodbav:"Image"`
}

func main() {
	cfg, err := config.LoadDefaultConfig(context.Background(), config.WithRegion("ap-southeast-2"))
	if err != nil {
		log.Fatal(err)
	}
	db := dynamodb.NewFromConfig(cfg)

	beers := []models.Beer{
		{ID: "1-pacific-ale", Name: "Pacific Ale", Brewery: "Stone & Wood", ABV: 4.4, Image: "beer_images/Stone_WoodPacificCan.webp"},
		{ID: "2-hazy-pale-ale", Name: "Hazy Pale Ale", Brewery: "Range Brewing", ABV: 5.2, Image: "beer_images/hazypale.webp"},
		{ID: "3-pale-ale", Name: "Pale Ale", Brewery: "Coopers Brewery", ABV: 4.5, Image: "beer_images/coopergreen.webp"},
		{ID: "4-zero-carb", Name: "Zero Carb", Brewery: "Better Beer", ABV: 4.2, Image: "beer_images/betterbeerzerocarb.png"},
		{ID: "5-ginger-beer", Name: "Ginger Beer", Brewery: "Better Beer", ABV: 4.0, Image: "beer_images/ginger_beer.webp"},
		{ID: "6-zero-alc", Name: "Zero Alc", Brewery: "Better Beer", ABV: 0.0, Image: "beer_images/zero_alc.webp"},
		{ID: "7-1857-bitter", Name: "1857 Bitter", Brewery: "Swan Brewery", ABV: 3.5, Image: ""},
		{ID: "8-1857-pilsener", Name: "1857 Pilsener", Brewery: "Swan Brewery", ABV: 4.8, Image: ""},
		{ID: "9-303-icegold", Name: "303 Icegold", Brewery: "Carlton and United", ABV: 3.3, Image: ""},
		{ID: "10-abbotsford-invalid-stout", Name: "Abbotsford Invalid Stout", Brewery: "Carlton and United", ABV: 5.6, Image: ""},
		{ID: "11-albany-ale", Name: "Albany Ale", Brewery: "The Rare Amber Brewing Co", ABV: 4.4, Image: ""},
		{ID: "12-amber-bitter", Name: "Amber Bitter", Brewery: "Toohey's", ABV: 3.5, Image: ""},
		{ID: "13-australian-white-beer", Name: "Australian White Beer", Brewery: "Malt Shovel Brewery", ABV: 5.0, Image: ""},
		{ID: "14-autumn-amber", Name: "Autumn Amber", Brewery: "Cascade", ABV: 5.0, Image: ""},
		{ID: "15-beamvar", Name: "Beamvar", Brewery: "Swanbourne Fermenting Co", ABV: 3.2, Image: ""},
		{ID: "16-beez-neez", Name: "Beez Neez", Brewery: "Gold Coast Brewery", ABV: 5.0, Image: ""},
		{ID: "17-beez-neez", Name: "Beez Neez", Brewery: "Matilda Bay", ABV: 4.7, Image: ""},
		{ID: "18-blue-tongue-premium-lager", Name: "Blue Tongue Premium Lager", Brewery: "Blue Tongue Brewery", ABV: 4.9, Image: ""},
		{ID: "19-boag's-bitter", Name: "Boag's Bitter", Brewery: "J. Boag & Son", ABV: 4.9, Image: ""},
		{ID: "20-boag's-draught", Name: "Boag's Draught", Brewery: "J. Boag & Son", ABV: 4.7, Image: ""},
		{ID: "21-boag's-light-draught", Name: "Boag's Light Draught", Brewery: "J. Boag & Son", ABV: 2.7, Image: ""},
		{ID: "22-boag's-strongarm-bitter", Name: "Boag's Strongarm Bitter", Brewery: "J. Boag & Son", ABV: 5.4, Image: ""},
		{ID: "23-boag's-xxx-ale", Name: "Boag's XXX Ale", Brewery: "J. Boag & Son", ABV: 4.8, Image: ""},
		{ID: "24-boags-1881-traditional-ale", Name: "Boags 1881 Traditional Ale", Brewery: "J. Boag & Son", ABV: 5.5, Image: ""},
		{ID: "25-bohemian-pilsner", Name: "Bohemian Pilsner", Brewery: "Carlton and United", ABV: 4.7, Image: ""},
		{ID: "26-bohemian-pilzner", Name: "Bohemian Pilzner", Brewery: "Matilda Bay", ABV: 4.7, Image: ""},
		{ID: "27-bootleg-bitter-beer", Name: "Bootleg Bitter Beer", Brewery: "Bootleg Brewery", ABV: 5.3, Image: ""},
		{ID: "28-bootleg-jazz-beer", Name: "Bootleg Jazz Beer", Brewery: "Bootleg Brewery", ABV: 6.9, Image: ""},
		{ID: "29-bootleg-light-beer", Name: "Bootleg Light Beer", Brewery: "Bootleg Brewery", ABV: 3.3, Image: ""},
		{ID: "30-bootleg-pilsener", Name: "Bootleg Pilsener", Brewery: "Bootleg Brewery", ABV: 4.7, Image: ""},
		{ID: "31-bootleg-raging-bull", Name: "Bootleg Raging Bull", Brewery: "Bootleg Brewery", ABV: 7.1, Image: ""},
		{ID: "32-bootleg-wheat-beer", Name: "Bootleg Wheat Beer", Brewery: "Bootleg Brewery", ABV: 4.7, Image: ""},
		{ID: "33-boranup-bitter", Name: "Boranup Bitter", Brewery: "Leahdale Brewery", ABV: 4.0, Image: ""},
		{ID: "34-brewer's-pilsener", Name: "Brewer's Pilsener", Brewery: "Grand Ridge", ABV: 4.9, Image: ""},
		{ID: "35-bright-ale", Name: "Bright Ale", Brewery: "Little Creatures Brewing P/L", ABV: 4.5, Image: ""},
		{ID: "36-buckley's", Name: "Buckley's", Brewery: "Yarra Flats Brewery", ABV: 4.5, Image: ""},
		{ID: "37-bullant-bitter-ale", Name: "Bullant Bitter Ale", Brewery: "Inchant Brewing Co", ABV: 5.5, Image: ""},
		{ID: "38-bullant-bitter-ale-light", Name: "Bullant Bitter Ale Light", Brewery: "Inchant Brewing Co", ABV: 3.5, Image: ""},
		{ID: "39-bundaberg-premium", Name: "Bundaberg Premium", Brewery: "Bundaberg Distilling", ABV: 5.0, Image: ""},
		{ID: "40-burke's-premium-hemp-filtered-ale", Name: "Burke's Premium Hemp Filtered Ale", Brewery: "Burke's Brewing Co", ABV: 4.9, Image: ""},
		{ID: "41-calton-d-ale", Name: "Calton D Ale", Brewery: "Carlton and United", ABV: 4.6, Image: ""},
		{ID: "42-cane-toad-beer", Name: "Cane Toad Beer", Brewery: "Gold Coast Brewery", ABV: 7.0, Image: ""},
		{ID: "43-carbine-stout", Name: "Carbine Stout", Brewery: "Castlemaine Perkins", ABV: 5.1, Image: ""},
		{ID: "44-carlton-black", Name: "Carlton Black", Brewery: "Carlton and United", ABV: 4.4, Image: ""},
		{ID: "45-carlton-cold-filtered", Name: "Carlton Cold Filtered", Brewery: "Carlton and United", ABV: 4.9, Image: ""},
		{ID: "46-carlton-lj-beer", Name: "Carlton LJ Beer", Brewery: "Carlton and United", ABV: 4.6, Image: ""},
		{ID: "47-carlton-mid-strength-bitter", Name: "Carlton Mid Strength Bitter", Brewery: "Carlton and United", ABV: 3.5, Image: ""},
		{ID: "48-bitter-beer", Name: "Bitter Beer", Brewery: "Cascade", ABV: 4.8, Image: ""},
		{ID: "49-blonde", Name: "Blonde", Brewery: "Cascade", ABV: 4.8, Image: ""},
		{ID: "50-draught", Name: "Draught", Brewery: "Cascade", ABV: 4.7, Image: ""},
		{ID: "51-export-stout", Name: "Export Stout", Brewery: "Cascade", ABV: 5.8, Image: ""},
		{ID: "52-light-lager", Name: "Light Lager", Brewery: "Cascade", ABV: 2.7, Image: ""},
		{ID: "53-pale-ale", Name: "Pale Ale", Brewery: "Cascade", ABV: 5.2, Image: ""},
		{ID: "54-premium-lager", Name: "Premium Lager", Brewery: "Cascade", ABV: 4.8, Image: ""},
		{ID: "55-premium-light", Name: "Premium Light", Brewery: "Cascade", ABV: 2.9, Image: ""},
		{ID: "56-special-stout", Name: "Special Stout", Brewery: "Cascade", ABV: 5.8, Image: ""},
		{ID: "57-spring-fest", Name: "Spring Fest", Brewery: "Cascade", ABV: 5.0, Image: ""},
		{ID: "58-castlemaine-special-dry", Name: "Castlemaine Special Dry", Brewery: "Castlemaine Perkins", ABV: 5.0, Image: ""},
		{ID: "59-castlemaine-xxxx-bitter", Name: "Castlemaine XXXX Bitter", Brewery: "Castlemaine Perkins", ABV: 4.8, Image: ""},
		{ID: "60-castlemaine-xxxx-light-bitter", Name: "Castlemaine XXXX Light Bitter", Brewery: "Castlemaine Perkins", ABV: 2.7, Image: ""},
		{ID: "61-classic-bitter", Name: "Classic Bitter", Brewery: "Tasmanian Breweries", ABV: 4.9, Image: ""},
		{ID: "62-classic-light", Name: "Classic Light", Brewery: "J. Boag & Son", ABV: 2.8, Image: ""},
		{ID: "63-colstar", Name: "Colstar", Brewery: "n Brewing Company", ABV: 0.05, Image: ""},
		{ID: "64-coonawarra-pale-ale", Name: "Coonawarra Pale Ale", Brewery: "Grand Ridge", ABV: 4.5, Image: ""},
		{ID: "65-best-extra-stout", Name: "Best Extra Stout", Brewery: "Cooper's", ABV: 6.8, Image: ""},
		{ID: "66-black-crow", Name: "Black Crow", Brewery: "Cooper's", ABV: 3.6, Image: ""},
		{ID: "67-dark-ale", Name: "Dark Ale", Brewery: "Cooper's", ABV: 4.5, Image: ""},
		{ID: "68-db", Name: "DB", Brewery: "Cooper's", ABV: 4.4, Image: ""},
		{ID: "69-extra-strong-vintage-ale", Name: "Extra Strong Vintage Ale", Brewery: "Cooper's", ABV: 7.1, Image: ""},
		{ID: "70-light", Name: "Light", Brewery: "Cooper's", ABV: 2.9, Image: ""},
		{ID: "71-original-pale-ale", Name: "Original Pale Ale", Brewery: "Cooper's", ABV: 4.8, Image: ""},
		{ID: "72-premium-clear-ale", Name: "Premium Clear Ale", Brewery: "Cooper's", ABV: 4.9, Image: ""},
		{ID: "73-sparkling-ale", Name: "Sparkling Ale", Brewery: "Cooper's", ABV: 5.8, Image: ""},
		{ID: "74-coopers-db", Name: "Coopers DB", Brewery: "Cooper's", ABV: 4.4, Image: ""},
		{ID: "75-crown-lager", Name: "Crown Lager", Brewery: "Carlton and United", ABV: 4.9, Image: ""},
		{ID: "76-d-beer", Name: "D-Beer", Brewery: "Cascade", ABV: 3.7, Image: ""},
		{ID: "77-dark-ice", Name: "Dark Ice", Brewery: "Hahn Brewing Co", ABV: 4.9, Image: ""},
		{ID: "78-diamond", Name: "Diamond", Brewery: "Carlton and United", ABV: 4.2, Image: ""},
		{ID: "79-dogbolter-special-dark-lager", Name: "Dogbolter Special Dark Lager", Brewery: "Matilda Bay", ABV: 5.2, Image: ""},
		{ID: "80-doyles-fisherman's-lager", Name: "Doyles Fisherman's Lager", Brewery: "Malt Shovel Brewery", ABV: 5.0, Image: ""},
		{ID: "81-empire", Name: "Empire", Brewery: "Carlton and United", ABV: 4.6, Image: ""},
		{ID: "82-emu-bitter", Name: "Emu Bitter", Brewery: "Swan Brewery", ABV: 4.6, Image: ""},
		{ID: "83-emu-draft", Name: "Emu Draft", Brewery: "Swan Brewery", ABV: 3.5, Image: ""},
		{ID: "84-emu-draft-bitter", Name: "Emu Draft Bitter", Brewery: "Swan Brewery", ABV: 3.5, Image: ""},
		{ID: "85-emu-export", Name: "Emu Export", Brewery: "Swan Brewery", ABV: 4.9, Image: ""},
		{ID: "86-lager", Name: "Lager", Brewery: "Eumundi", ABV: 4.8, Image: ""},
		{ID: "87-light", Name: "Light", Brewery: "Eumundi", ABV: 2.7, Image: ""},
		{ID: "88-first-harvest-ale-2002", Name: "First Harvest Ale 2002", Brewery: "Cascade", ABV: 5.5, Image: ""},
		{ID: "89-foster's-extra-lager", Name: "Foster's Extra Lager", Brewery: "Carlton and United", ABV: 5.5, Image: ""},
		{ID: "90-foster's-lager", Name: "Foster's Lager", Brewery: "Carlton and United", ABV: 4.9, Image: ""},
		{ID: "91-foster's-light-ice", Name: "Foster's Light Ice", Brewery: "Carlton and United", ABV: 2.7, Image: ""},
		{ID: "92-foster's-special-bitter", Name: "Foster's Special Bitter", Brewery: "Carlton and United", ABV: 2.8, Image: ""},
		{ID: "93-full-sail", Name: "Full Sail", Brewery: "Harbour Brewing Co", ABV: 4.9, Image: ""},
		{ID: "94-", Name: "", Brewery: "Gage Roads", ABV: 4.7, Image: ""},
		{ID: "95-lager", Name: "Lager", Brewery: "Gage Roads", ABV: 4.7, Image: ""},
		{ID: "96-genuine-cold-filtered-draught", Name: "Genuine Cold-Filtered Draught", Brewery: "Cooper's", ABV: 4.5, Image: ""},
		{ID: "97-gippsland-gold", Name: "Gippsland Gold", Brewery: "Grand Ridge", ABV: 4.9, Image: ""},
		{ID: "98-golden-ale", Name: "Golden Ale", Brewery: "Malt Shovel Brewery", ABV: 4.5, Image: ""},
		{ID: "99-good-ale-mead", Name: "Good Ale Mead", Brewery: "Taverner's", ABV: 8.0, Image: ""},
		{ID: "100-governor-broome", Name: "Governor Broome", Brewery: "Broome Brewery", ABV: 5.0, Image: ""},
		{ID: "101-guildford-porter", Name: "Guildford Porter", Brewery: "Inchant Brewing Co", ABV: 6.0, Image: ""},
		{ID: "102-haagen-premium-malt", Name: "Haagen Premium Malt", Brewery: "Independent Breweries", ABV: 5.0, Image: ""},
		{ID: "103-hahn-gold", Name: "Hahn Gold", Brewery: "Hahn Brewing Co", ABV: 3.5, Image: ""},
		{ID: "104-hahn-gold-cold-filtered", Name: "Hahn Gold Cold Filtered", Brewery: "Hahn Brewing Co", ABV: 3.5, Image: ""},
		{ID: "105-hahn-ice", Name: "Hahn Ice", Brewery: "Hahn Brewing Co", ABV: 4.9, Image: ""},
		{ID: "106-hahn-premium", Name: "Hahn Premium", Brewery: "Hahn Brewing Co", ABV: 5.0, Image: ""},
		{ID: "107-hahn-premium-light", Name: "Hahn Premium Light", Brewery: "Hahn Brewing Co", ABV: 2.7, Image: ""},
		{ID: "108-hat-lifter-stout", Name: "Hat Lifter Stout", Brewery: "Grand Ridge", ABV: 4.9, Image: ""},
		{ID: "109-heritage", Name: "Heritage", Brewery: "Cooper's", ABV: 5.2, Image: ""},
		{ID: "110-hightail-ale", Name: "Hightail Ale", Brewery: "Mountain Goat Beer", ABV: 4.5, Image: ""},
		{ID: "111-holgate-old-pale-ale", Name: "Holgate Old Pale Ale", Brewery: "Holgate Brewery", ABV: 5.0, Image: ""},
		{ID: "112-india-pale-ale", Name: "India Pale Ale", Brewery: "Malt Shovel Brewery", ABV: 5.6, Image: ""},
		{ID: "113-j.-boag's-original-bitter", Name: "J. Boag's Original Bitter", Brewery: "J. Boag & Son", ABV: 4.7, Image: ""},
		{ID: "114-jack-russell", Name: "Jack Russell", Brewery: "Cooper's", ABV: 4.9, Image: ""},
		{ID: "115-james-boag's-premium", Name: "James Boag's Premium", Brewery: "J. Boag & Son", ABV: 5.0, Image: ""},
		{ID: "116-james-squire-ipa", Name: "James Squire IPA", Brewery: "Malt Shovel Brewery", ABV: 5.6, Image: ""},
		{ID: "117-james-squire-original-amber-ale", Name: "James Squire Original Amber Ale", Brewery: "Malt Shovel Brewery", ABV: 5.0, Image: ""},
		{ID: "118-james-squire-original-pilsener", Name: "James Squire Original Pilsener", Brewery: "Malt Shovel Brewery", ABV: 5.0, Image: ""},
		{ID: "119-james-squire-porter", Name: "James Squire Porter", Brewery: "Malt Shovel Brewery", ABV: 5.0, Image: ""},
		{ID: "120-jarrah-jacks-wheat-beer", Name: "Jarrah Jacks Wheat Beer", Brewery: "Pemberton Brewing Co", ABV: 5.1, Image: ""},
		{ID: "121-kent-old-brown", Name: "Kent Old Brown", Brewery: "Carlton and United", ABV: 4.4, Image: ""},
		{ID: "122-king-premium-lager", Name: "King Premium Lager", Brewery: "n Brewing Company", ABV: 4.9, Image: ""},
		{ID: "123-light-bitter", Name: "Light Bitter", Brewery: "Carlton and United", ABV: 2.8, Image: ""},
		{ID: "124-live", Name: "Live", Brewery: "Little Creatures Brewing P/L", ABV: 5.2, Image: ""},
		{ID: "125-longbrew-lager", Name: "Longbrew Lager", Brewery: "Hahn Brewing", ABV: 4.5, Image: ""},
		{ID: "126-lugger-beer", Name: "Lugger Beer", Brewery: "Broome Brewery", ABV: 7.0, Image: ""},
		{ID: "127-malthouse-real-ale", Name: "Malthouse Real Ale", Brewery: "Matilda Bay", ABV: 5.8, Image: ""},
		{ID: "128-mariner-bitter", Name: "Mariner Bitter", Brewery: "Fremantle Brewery", ABV: 5.0, Image: ""},
		{ID: "129-bitter", Name: "Bitter", Brewery: "Matilda Bay", ABV: 3.5, Image: ""},
		{ID: "130-maxim", Name: "Maxim", Brewery: "Toohey's", ABV: 4.6, Image: ""},
		{ID: "131-melbourne-bitter", Name: "Melbourne Bitter", Brewery: "Carlton and United", ABV: 4.9, Image: ""},
		{ID: "132-mez", Name: "Mez", Brewery: "South Australian Brewing Co", ABV: 5.5, Image: ""},
		{ID: "133-midland-fettler", Name: "Midland Fettler", Brewery: "Inchant Brewing Co", ABV: 6.3, Image: ""},
		{ID: "134-millenium-ale-hahn-special-vintage", Name: "Millenium Ale Hahn Special Vintage", Brewery: "Hahn Brewing Co", ABV: 8.0, Image: ""},
		{ID: "135-moonlite-pure-malt-beer", Name: "Moonlite Pure Malt Beer", Brewery: "Grand Ridge", ABV: 3.3, Image: ""},
		{ID: "136-mountain-ale", Name: "Mountain Ale", Brewery: "Jamieson Brewery", ABV: 4.0, Image: ""},
		{ID: "137-mt-macedon-ale", Name: "Mt Macedon Ale", Brewery: "Holgate Brewery", ABV: 4.5, Image: ""},
		{ID: "138-natural-cellar", Name: "Natural Cellar", Brewery: "Palatinat", ABV: 4.1, Image: ""},
		{ID: "139-new---genuine-draught", Name: "New - Genuine Draught", Brewery: "Toohey's", ABV: 4.8, Image: ""},
		{ID: "140-new-light", Name: "New Light", Brewery: "Cooper's", ABV: 2.9, Image: ""},
		{ID: "141-octoberfest-palatinat", Name: "Octoberfest Palatinat", Brewery: "Palatinat", ABV: 4.5, Image: ""},
		{ID: "142-old-ale", Name: "Old Ale", Brewery: "Coonawarra Lawrence Vistor", ABV: 5.0, Image: ""},
		{ID: "143-or-dark", Name: "or Dark", Brewery: "Palatinat", ABV: 4.1, Image: ""},
		{ID: "144-or-original-may-bock", Name: "or Original May Bock", Brewery: "Palatinat", ABV: 6.0, Image: ""},
		{ID: "145-palatinus-golden-lager", Name: "Palatinus Golden Lager", Brewery: "Palatinat", ABV: 4.5, Image: ""},
		{ID: "146-palatinus-light-lager", Name: "Palatinus Light Lager", Brewery: "Palatinat", ABV: 3.0, Image: ""},
		{ID: "147-us-smoker-wheat-beer", Name: "us Smoker Wheat Beer", Brewery: "Palatinat", ABV: 4.0, Image: ""},
		{ID: "148-pale-ale", Name: "Pale Ale", Brewery: "Geelong Brewing Co", ABV: 4.5, Image: ""},
		{ID: "149-pale-ale", Name: "Pale Ale", Brewery: "Mountain Goat Beer", ABV: 4.5, Image: ""},
		{ID: "150-pearl-lager", Name: "Pearl Lager", Brewery: "Broome Brewery", ABV: 3.4, Image: ""},
		{ID: "151-pi55-weak", Name: "Pi55 Weak", Brewery: "Pi55 Beer Co", ABV: 2.5, Image: ""},
		{ID: "152-pike's-oakbank-beer", Name: "Pike's Oakbank Beer", Brewery: "Pike's Oakbank Brewery", ABV: 4.9, Image: ""},
		{ID: "153-pils", Name: "Pils", Brewery: "Toohey's", ABV: 5.2, Image: ""},
		{ID: "154-piss", Name: "Piss", Brewery: "Piss Beer Co", ABV: 4.9, Image: ""},
		{ID: "155-power's-bitter", Name: "Power's Bitter", Brewery: "Queensland Breweries", ABV: 4.8, Image: ""},
		{ID: "156-power's-gold", Name: "Power's Gold", Brewery: "Queensland Breweries", ABV: 3.4, Image: ""},
		{ID: "157-power's-ice", Name: "Power's Ice", Brewery: "Queensland Breweries", ABV: 4.6, Image: ""},
		{ID: "158-power's-light", Name: "Power's Light", Brewery: "Queensland Breweries", ABV: 2.8, Image: ""},
		{ID: "159-premier-lager", Name: "Premier Lager", Brewery: "Matilda Bay", ABV: 3.4, Image: ""},
		{ID: "160-premium", Name: "Premium", Brewery: "Geelong Brewing Co", ABV: 4.9, Image: ""},
		{ID: "161-premium-dry", Name: "Premium Dry", Brewery: "Carlton and United", ABV: 5.0, Image: ""},
		{ID: "162-premium-lager", Name: "Premium Lager", Brewery: "Carlton and United", ABV: 3.4, Image: ""},
		{ID: "164-premium-light", Name: "Premium Light", Brewery: "J. Boag & Son", ABV: 2.9, Image: ""},
		{ID: "165-premium-pilsener-lager", Name: "Premium Pilsener Lager", Brewery: "Matilda Bay", ABV: 4.9, Image: ""},
		{ID: "166-pure-blonde", Name: "Pure Blonde", Brewery: "Carlton and United", ABV: 4.6, Image: ""},
		{ID: "167-real-bitter-ale", Name: "Real Bitter Ale", Brewery: "Reschs", ABV: 4.6, Image: ""},
		{ID: "168-red-ant", Name: "Red Ant", Brewery: "Jerningham St. Brewery", ABV: 4.5, Image: ""},
		{ID: "169-red-back-original", Name: "Red Back Original", Brewery: "Matilda Bay", ABV: 4.7, Image: ""},
		{ID: "170-red-bitter-beer", Name: "Red Bitter Beer", Brewery: "Toohey's", ABV: 5.0, Image: ""},
		{ID: "171-red-dog", Name: "Red Dog", Brewery: "Matilda Bay", ABV: 5.0, Image: ""},
		{ID: "172-redback-light", Name: "Redback Light", Brewery: "Matilda Bay", ABV: 3.4, Image: ""},
		{ID: "173-regency-light", Name: "Regency Light", Brewery: "Cooper's", ABV: 2.0, Image: ""},
		{ID: "174-pilsner", Name: "Pilsner", Brewery: "Reschs", ABV: 4.6, Image: ""},
		{ID: "175-rogers'", Name: "Rogers'", Brewery: "Little Creatures Brewing P/L", ABV: 3.8, Image: ""},
		{ID: "176-roof-top-real-lager", Name: "Roof Top Real Lager", Brewery: "Carlton and United", ABV: 4.7, Image: ""},
		{ID: "177-sanctuary-cove-premium-lager", Name: "Sanctuary Cove Premium Lager", Brewery: "Gold Coast Brewery", ABV: 4.9, Image: ""},
		{ID: "178-settler's-pale", Name: "Settler's Pale", Brewery: "Bootleg Brewery", ABV: 4.8, Image: ""},
		{ID: "179-sheaf-stout", Name: "Sheaf Stout", Brewery: "Carlton and United", ABV: 5.7, Image: ""},
		{ID: "180-southern-draught", Name: "Southern Draught", Brewery: "Cascade", ABV: 4.8, Image: ""},
		{ID: "181-southwark-bitter", Name: "Southwark Bitter", Brewery: "South Australian Brewing Co", ABV: 4.5, Image: ""},
		{ID: "182-southwark-black-ale", Name: "Southwark Black Ale", Brewery: "South Australian Brewing Co", ABV: 4.4, Image: ""},
		{ID: "183-southwark-old-stout", Name: "Southwark Old Stout", Brewery: "South Australian Brewing Co", ABV: 7.4, Image: ""},
		{ID: "184-southwark-premium-lager", Name: "Southwark Premium Lager", Brewery: "South Australian Brewering Co", ABV: 5.2, Image: ""},
		{ID: "185-southwark-white-beer", Name: "Southwark White Beer", Brewery: "South Australian Brewing Co", ABV: 5.0, Image: ""},
		{ID: "186-sovereign", Name: "Sovereign", Brewery: "Carlton and United", ABV: 2.5, Image: ""},
		{ID: "187-sovereign-superior-lager", Name: "Sovereign Superior Lager", Brewery: "Castlemaine Perkins", ABV: 3.8, Image: ""},
		{ID: "188-sparkling-xxx", Name: "Sparkling XXX", Brewery: "Castlemaine Perkins", ABV: 5.2, Image: ""},
		{ID: "190-st-george", Name: "St George", Brewery: "J. Boag & Son", ABV: 4.8, Image: ""},
		{ID: "191-stockade", Name: "Stockade", Brewery: "Stockade Brewery", ABV: 5.0, Image: ""},
		{ID: "192-summer-wheat-beer", Name: "Summer Wheat Beer", Brewery: "Malt Shovel Brewery", ABV: 5.0, Image: ""},
		{ID: "193-supershine", Name: "Supershine", Brewery: "Grand Ridge", ABV: 11.0, Image: ""},
		{ID: "194-surefoot-stout", Name: "Surefoot Stout", Brewery: "Mountain Goat Beer", ABV: 5.0, Image: ""},
		{ID: "195-swan-draught", Name: "Swan Draught", Brewery: "Swan Brewery", ABV: 4.8, Image: ""},
		{ID: "196-swan-gold", Name: "Swan Gold", Brewery: "Swan Brewery", ABV: 3.5, Image: ""},
		{ID: "197-swan-lager", Name: "Swan Lager", Brewery: "Swan Brewery", ABV: 4.9, Image: ""},
		{ID: "198-swan-light", Name: "Swan Light", Brewery: "Swan Brewery", ABV: 0.9, Image: ""},
		{ID: "199-swan-mid", Name: "Swan Mid", Brewery: "Swan Brewery", ABV: 3.5, Image: ""},
		{ID: "200-swan-stout", Name: "Swan Stout", Brewery: "Swan Brewery", ABV: 6.8, Image: ""},
		{ID: "201-sydney-bitter", Name: "Sydney Bitter", Brewery: "Toohey's", ABV: 4.9, Image: ""},
		{ID: "202-tasman-bitter", Name: "Tasman Bitter", Brewery: "Tasmanian Breweries", ABV: 4.8, Image: ""},
		{ID: "203-tasman-ice", Name: "Tasman Ice", Brewery: "Tasmanian Breweries", ABV: 4.9, Image: ""},
		{ID: "204-tasman-special-bitter", Name: "Tasman Special Bitter", Brewery: "Tasmanian Breweries", ABV: 2.8, Image: ""},
		{ID: "205-tenterfield-saddler-1870", Name: "Tenterfield Saddler 1870", Brewery: "Gold Coast Brewery", ABV: 4.9, Image: ""},
		{ID: "206-thomas-cooper's-finest-export-beer", Name: "Thomas Cooper's Finest Export Beer", Brewery: "Cooper's", ABV: 4.9, Image: ""},
		{ID: "207-thomas-jecks-commonwealth-ale", Name: "Thomas Jecks Commonwealth Ale", Brewery: "Inchant Brewing Co", ABV: 4.5, Image: ""},
		{ID: "208-tiger-head-bitter-beer", Name: "Tiger Head Bitter Beer", Brewery: "Cascade", ABV: 2.8, Image: ""},
		{ID: "209-tom's-brown", Name: "Tom's Brown", Brewery: "Bootleg Brewery", ABV: 4.0, Image: ""},
		{ID: "210-", Name: "", Brewery: "Tomahawk", ABV: 4.9, Image: ""},
		{ID: "211-christmas-brew", Name: "Christmas Brew", Brewery: "Toohey's", ABV: 5.0, Image: ""},
		{ID: "212-draught", Name: "Draught", Brewery: "Toohey's", ABV: 4.6, Image: ""},
		{ID: "213-extra-dry", Name: "Extra Dry", Brewery: "Toohey's", ABV: 5.0, Image: ""},
		{ID: "214-gold-bitter-beer", Name: "Gold Bitter Beer", Brewery: "Toohey's", ABV: 3.4, Image: ""},
		{ID: "215-old-black-ale", Name: "Old Black Ale", Brewery: "Toohey's", ABV: 4.4, Image: ""},
		{ID: "216-vb-original-ale", Name: "VB Original Ale", Brewery: "Carlton and United", ABV: 4.6, Image: ""},
		{ID: "217-victoria-bitter", Name: "Victoria Bitter", Brewery: "Carlton and United", ABV: 4.9, Image: ""},
		{ID: "218-vienna-red", Name: "Vienna Red", Brewery: "Hahn Brewing Co", ABV: 5.0, Image: ""},
		{ID: "219-wa-gold", Name: "WA Gold", Brewery: "Carlton and United", ABV: 3.0, Image: ""},
		{ID: "220-west-end-draught", Name: "West End Draught", Brewery: "South Australian Brewering Co", ABV: 4.5, Image: ""},
		{ID: "221-west-end-gold", Name: "West End Gold", Brewery: "South Australian Brewing Co", ABV: 3.5, Image: ""},
		{ID: "222-west-end-light", Name: "West End Light", Brewery: "South Australian Brewing Co", ABV: 2.7, Image: ""},
		{ID: "223-white-lightning-dingo-bitter", Name: "White Lightning Dingo Bitter", Brewery: "Geelong Brewing Co", ABV: 4.9, Image: ""},
		{ID: "224-winter-ale", Name: "Winter Ale", Brewery: "Holgate Brewery", ABV: 6.0, Image: ""},
		{ID: "225-witbier", Name: "Witbier", Brewery: "Hahn Brewing Co", ABV: 5.0, Image: ""},
		{ID: "226-wodonga-wheat-beer", Name: "Wodonga Wheat Beer", Brewery: "Palatinat", ABV: 4.0, Image: ""},
		{ID: "227-xxxx-dl-lager", Name: "XXXX DL Lager", Brewery: "Castlemaine Perkins", ABV: 4.4, Image: ""},
		{ID: "228-xxxx-gold", Name: "XXXX Gold", Brewery: "Castlemaine Perkins", ABV: 3.5, Image: ""},
		{ID: "229-xxxx-light-bitter", Name: "XXXX Light Bitter", Brewery: "Castlemaine Perkins", ABV: 2.5, Image: ""},
		{ID: "230-xxxx-original-draught", Name: "XXXX Original Draught", Brewery: "Castlemaine Perkins", ABV: 4.8, Image: ""},
		{ID: "231-yarra-valley-gold", Name: "Yarra Valley Gold", Brewery: "Grand Ridge", ABV: 4.9, Image: ""},
		{ID: "232-premium-beer", Name: "Premium Beer", Brewery: "Sapporo Breweries", ABV: 5.0, Image: "beer_images/Screenshot_2025-10-24_152748.png"},
		{ID: "233-super-dry", Name: "Super Dry", Brewery: "Hahn Brewing Co", ABV: 4.6, Image: "beer_images/Screenshot_2025-10-24_153037.png"},
		{ID: "234-james-st.-premium-lager", Name: "James St. Premium Lager", Brewery: "Valley Hops Brewing", ABV: 4.9, Image: "beer_images/Valley-Hops-Brewing-James-St-Premium-Lager-F.png"},
		{ID: "235-geezer-smooth-ale", Name: "Geezer Smooth Ale", Brewery: "Valley Hops Brewing", ABV: 4.1, Image: "beer_images/Valley-Hops-Brewing-Geezer-Smooth-Ale.png"},
		{ID: "236-interloper-hazy-ipa", Name: "Interloper Hazy IPA", Brewery: "Valley Hops Brewing", ABV: 6.0, Image: "beer_images/Valley-Hops-Brewing-Interloper-Hazy-IPA.png"},
		{ID: "237-diehards-mid-lager", Name: "Diehards Mid Lager", Brewery: "Valley Hops Brewing", ABV: 3.5, Image: "beer_images/Valley-Hops-Brewing-Diehards-Mid-Lager.png"},
		{ID: "238-diehards-original-lager", Name: "Diehards Original Lager", Brewery: "Valley Hops Brewing", ABV: 4.5, Image: "beer_images/Valley-Hops-Brewing-Diehards-Original-Lager.png"},
		{ID: "239-21-pubs-pale-ale", Name: "21 Pubs Pale Ale", Brewery: "Valley Hops Brewing", ABV: 5.0, Image: "beer_images/Valley-Hops-Brewing-21-Pubs-Pale-Ale.png"},
		{ID: "240-exhibitionist-xpa", Name: "Exhibitionist XPA", Brewery: "Valley Hops Brewing", ABV: 4.2, Image: "beer_images/Valley-Hops-Brewing-Exhibitionist-XPA-768x1016.png"},
		{ID: "241-pabst-blue-ribbon", Name: "Pabst Blue Ribbon", Brewery: "Pabst Brewing Company", ABV: 4.7, Image: "beer_images/717160-1.webp"},
		{ID: "242-super-dry", Name: "Super Dry", Brewery: "Asahi Group", ABV: 5.0, Image: "beer_images/98903-1.png"},
		{ID: "243-paradise-ipa", Name: "Paradise IPA", Brewery: "Felon's Brewing Co", ABV: 6.0, Image: "beer_images/ParadiseIPAMe_Uspecs_1400x.webp"},
		{ID: "244-paloma-sour", Name: "Paloma Sour", Brewery: "Felon's Brewing Co", ABV: 4.5, Image: "beer_images/Untitled_design-10_9f4e148f-e487-4f85-8495-15a421e69086_1200x.webp"},
		{ID: "245-mid-crush", Name: "Mid Crush", Brewery: "Felon's Brewing Co", ABV: 3.5, Image: "beer_images/corerangeecomm4_1400x.webp"},
		{ID: "246-ipa", Name: "IPA", Brewery: "Felon's Brewing Co", ABV: 6.2, Image: "beer_images/RQA__IPA_Trophie_1000x.webp"},
		{ID: "247-australian-pale-ale", Name: "Australian Pale Ale", Brewery: "Felon's Brewing Co", ABV: 5.0, Image: "beer_images/Indies_Ecomm2_1000x.webp"},
		{ID: "248-galaxy-haze", Name: "Galaxy Haze", Brewery: "Felon's Brewing Co", ABV: 4.4, Image: "beer_images/corerangeecomm3_1400x.webp"},
		{ID: "249-crisp-lager", Name: "Crisp Lager", Brewery: "Felon's Brewing Co", ABV: 4.2, Image: "beer_images/Indies_Ecomm_1000x.webp"},
		{ID: "250-super-dry-lager", Name: "Super Dry Lager", Brewery: "Asahi", ABV: 3.5, Image: "beer_images/asahi-super-dry-cans-500ml.png"},
		{ID: "251-super-dry", Name: "Super Dry", Brewery: "Asahi", ABV: 5.0, Image: "beer_images/asahi-super-dry-cans-500ml.png"},
		{ID: "252-cerveza", Name: "Cerveza", Brewery: "Balter", ABV: 4.0, Image: "beer_images/balter-cerveza-cans-375ml.png"},
		{ID: "253-hazy-ipa", Name: "Hazy Ipa", Brewery: "Balter", ABV: 6.0, Image: "beer_images/balter-hazy-ipa-cans-375ml.png"},
		{ID: "254-xpa", Name: "Xpa", Brewery: "Balter", ABV: 5.0, Image: "beer_images/balter-xpa-cans-375ml.png"},
		{ID: "255-beer", Name: "Beer", Brewery: "Beck's", ABV: 4.0, Image: "beer_images/beck-s-beer-330ml.png"},
		{ID: "256-middy-lager", Name: "Middy Lager", Brewery: "Better Beer", ABV: 3.0, Image: "beer_images/better-beer-middy-lager-3-0-can-355ml.png"},
		{ID: "257-zero-carb-lager", Name: "Zero Carb Lager", Brewery: "Better Beer", ABV: 4.2, Image: "beer_images/better-beer-zero-carb-lager-can-355ml.png"},
		{ID: "258-lager-beer", Name: "Lager Beer", Brewery: "Budweiser", ABV: 4.5, Image: "beer_images/budweiser-lager-beer-bottle-330ml.png"},
		{ID: "259-premium-lager", Name: "Premium Lager", Brewery: "Byron Bay Brewery", ABV: 4.2, Image: "beer_images/byron-bay-brewery-premium-lager-bottles-355ml.png"},
		{ID: "260-", Name: "", Brewery: "Carlton Draught", ABV: 4.6, Image: "beer_images/carlton-draught-bottles-375ml.png"},
		{ID: "261-lager", Name: "Lager", Brewery: "Carlton Dry", ABV: 4.5, Image: "beer_images/carlton-dry-lager-cans-375ml.png"},
		{ID: "262-mid", Name: "Mid", Brewery: "Carlton", ABV: 3.5, Image: "beer_images/carlton-mid-750ml.png"},
		{ID: "263-australian-lager", Name: "Australian Lager", Brewery: "Coopers", ABV: 4.2, Image: "beer_images/coopers-australian-lager-cans-375ml.png"},
		{ID: "264-best-extra-stout", Name: "Best Extra Stout", Brewery: "Coopers", ABV: 6.3, Image: "beer_images/coopers-best-extra-stout-750ml.png"},
		{ID: "265-mild-ale", Name: "Mild Ale", Brewery: "Coopers", ABV: 3.5, Image: "beer_images/coopers-mild-ale-bottles-375ml.png"},
		{ID: "266-original-pale-ale", Name: "Original Pale Ale", Brewery: "Coopers", ABV: 4.5, Image: "beer_images/coopers-original-pale-ale-cans-375ml.png"},
		{ID: "267-sparkling-ale", Name: "Sparkling Ale", Brewery: "Coopers", ABV: 5.8, Image: "beer_images/coopers-sparkling-ale-cans-375ml.png"},
		{ID: "268-xpa", Name: "Xpa", Brewery: "Coopers", ABV: 5.2, Image: "beer_images/coopers-xpa-cans-375ml.png"},
		{ID: "269-extra-beer", Name: "Extra Beer", Brewery: "Corona", ABV: 4.5, Image: "beer_images/corona-extra-beer-bottles-355ml.png"},
		{ID: "270-lager", Name: "Lager", Brewery: "Crown", ABV: 4.9, Image: "beer_images/crown-lager-bottles-375ml.png"},
		{ID: "271-original-refreshing-ale", Name: "Original Refreshing Ale", Brewery: "Furphy", ABV: 4.4, Image: "beer_images/furphy-original-refreshing-ale-cans-375ml.png"},
		{ID: "272-refreshing-ale", Name: "Refreshing Ale", Brewery: "Furphy", ABV: 4.4, Image: "beer_images/furphy-refreshing-ale-cans-375ml.png"},
		{ID: "273-original", Name: "Original", Brewery: "Great Northern Brewing Co.", ABV: 4.2, Image: "beer_images/great-northern-brewing-co-original-cans-375ml.png"},
		{ID: "274-original-lager", Name: "Original Lager", Brewery: "Great Northern Brewing Co.", ABV: 4.2, Image: "beer_images/great-northern-brewing-co-original-lager-bottles-700ml.png"},
		{ID: "275-super-crisp-lager", Name: "Super Crisp Lager", Brewery: "Great Northern Brewing Co.", ABV: 3.5, Image: "beer_images/great-northern-brewing-co-super-crisp-lager-700ml.png"},
		{ID: "276-zero", Name: "Zero", Brewery: "Great Northern Brewing Co.", ABV: 0.0, Image: "beer_images/great-northern-brewing-co-zero-bottles-330ml.png"},
		{ID: "277-super-dry", Name: "Super Dry", Brewery: "Hahn", ABV: 4.6, Image: "beer_images/hahn-super-dry-cans-375ml.png"},
		{ID: "278-super-dry-lager-3.5-percentage", Name: "Super Dry Lager 3.5 Percentage", Brewery: "Hahn", ABV: 3.5, Image: "beer_images/hahn-super-dry-lager-3-5-percentage-bottle-330ml.png"},
		{ID: "279-super-dry-lager", Name: "Super Dry Lager", Brewery: "Hahn", ABV: 4.6, Image: "beer_images/hahn-super-dry-lager-cans-375ml.png"},
		{ID: "280-superdry-gluten-free-bottle", Name: "Superdry Gluten Free Bottle", Brewery: "Hahn", ABV: 4.2, Image: "beer_images/hahn-superdry-gluten-free-330ml-bottle.png"},
		{ID: "281-ultra-zero-carb", Name: "Ultra Zero Carb", Brewery: "Hahn", ABV: 4.2, Image: "beer_images/hahn-ultra-zero-carb-can-375ml.png"},
		{ID: "282-", Name: "", Brewery: "Heineken", ABV: 5.0, Image: "beer_images/heineken-cans-500ml.png"},
		{ID: "283-lager", Name: "Lager", Brewery: "Heineken", ABV: 5.0, Image: "beer_images/heineken-lager-bottles-330ml.png"},
		{ID: "284-zero", Name: "Zero", Brewery: "Heineken", ABV: 0.0, Image: "beer_images/heineken-zero-bottle-330ml.png"},
		{ID: "285-beer", Name: "Beer", Brewery: "Hollandia", ABV: 4.7, Image: "beer_images/hollandia-beer-650ml.png"},
		{ID: "286-lager", Name: "Lager", Brewery: "Hollandia", ABV: 4.7, Image: "beer_images/hollandia-lager-330ml.png"},
		{ID: "287-crisp-lager", Name: "Crisp Lager", Brewery: "Iron Jack", ABV: 3.3, Image: "beer_images/iron-jack-crisp-lager-cans-375ml.png"},
		{ID: "288-150-lashes-premium-pale-ale", Name: "150 Lashes Premium Pale Ale", Brewery: "James Squire", ABV: 4.2, Image: "beer_images/james-squire-150-lashes-premium-pale-ale-bottles-330ml.png"},
		{ID: "289-pale-ale", Name: "Pale Ale", Brewery: "Little Creatures", ABV: 5.2, Image: "beer_images/little-creatures-xpa-330ml.png"},
		{ID: "290-chill-with-lime-lager", Name: "Chill With Lime Lager", Brewery: "Miller", ABV: 4.0, Image: "beer_images/miller-chill-with-lime-lager-bottles-330ml.png"},
		{ID: "291-okinawa-premium-draft", Name: "Okinawa Premium Draft", Brewery: "Monsuta", ABV: 5.0, Image: "beer_images/monsuta-okinawa-premium-draft-can-500ml.png"},
		{ID: "292-very-enjoyable-beer", Name: "Very Enjoyable Beer", Brewery: "Mountain Goat", ABV: 4.2, Image: "beer_images/mountain-goat-very-enjoyable-beer-cans-375ml.png"},
		{ID: "293-pils", Name: "Pils", Brewery: "Oettinger", ABV: 4.7, Image: "beer_images/oettinger-pils-cans-500ml.png"},
		{ID: "294-", Name: "", Brewery: "Peroni Nastro Azzurro", ABV: 5.0, Image: "beer_images/peroni-nastro-azzurro-bottles-330ml.png"},
		{ID: "295-nastro-azzurro", Name: "Nastro Azzurro", Brewery: "Peroni Nastro Azzurro", ABV: 3.5, Image: "beer_images/peroni-nastro-azzurro-nastro-azzurro-3-5-bottles-330ml.png"},
		{ID: "296-south-coast-pale-ale", Name: "South Coast Pale Ale", Brewery: "Pirate Life", ABV: 4.4, Image: "beer_images/pirate-life-south-coast-pale-ale-cans-355ml.png"},
		{ID: "297-ultra-low-carb", Name: "Ultra Low Carb", Brewery: "Pure Blonde", ABV: 4.2, Image: "beer_images/pure-blonde-ultra-low-carb-bottles-330ml.png"},
		{ID: "298-ultra-low-carb-lager", Name: "Ultra Low Carb Lager", Brewery: "Pure Blonde", ABV: 4.2, Image: "beer_images/pure-blonde-ultra-low-carb-lager-cans-375ml.png"},
		{ID: "299-premium-lager", Name: "Premium Lager", Brewery: "Sapporo", ABV: 5.0, Image: "beer_images/sapporo-premium-lager-cans-650ml.png"},
		{ID: "300-cerveza-original", Name: "Cerveza Original", Brewery: "Sol", ABV: 4.2, Image: "beer_images/sol-cerveza-original-bottles-330ml.png"},
		{ID: "301-blonde-low-carb-beer", Name: "Blonde Low Carb Beer", Brewery: "Steersman", ABV: 4.2, Image: "beer_images/steersman-blonde-low-carb-beer-330ml.png"},
		{ID: "302-ultra-dry-beer", Name: "Ultra Dry Beer", Brewery: "Steersman", ABV: 4.2, Image: "beer_images/steersman-ultra-crisp-beer-330ml.png"},
		{ID: "303-", Name: "", Brewery: "Stella Artois", ABV: 4.8, Image: "beer_images/stella-artois-cans-500ml.png"},
		{ID: "305-extra-dry", Name: "Extra Dry", Brewery: "Tooheys", ABV: 4.4, Image: "beer_images/tooheys-extra-dry-cans-375ml.png"},
		{ID: "306-new", Name: "New", Brewery: "Tooheys", ABV: 4.6, Image: "beer_images/tooheys-new-cans-375ml.png"},
		{ID: "307-blue-light", Name: "Blue Light", Brewery: "Tun", ABV: 2.7, Image: "beer_images/tun-blue-light-cans-330ml.png"},
		{ID: "308-gold-mid", Name: "Gold Mid", Brewery: "Tun", ABV: 3.3, Image: "beer_images/tun-gold-mid-cans-330ml.png"},
		{ID: "309-green-bitter", Name: "Green Bitter", Brewery: "Tun", ABV: 4.9, Image: "beer_images/tun-green-bitter-cans-330ml.png"},
		{ID: "310-red-draught", Name: "Red Draught", Brewery: "Tun", ABV: 4.0, Image: "beer_images/tun-red-draught-cans-330ml.png"},
		{ID: "311-", Name: "", Brewery: "Victoria Bitter", ABV: 4.9, Image: "beer_images/victoria-bitter-750ml.png"},
		{ID: "312-lager", Name: "Lager", Brewery: "Victoria Bitter", ABV: 4.9, Image: "beer_images/victoria-bitter-750ml.png"},
		{ID: "313-gold", Name: "Gold", Brewery: "XXXX", ABV: 3.5, Image: "beer_images/xxxx-gold-cans-375ml.png"},
		{ID: "314-gold-mid-strength-lager", Name: "Gold Mid Strength Lager", Brewery: "XXXX", ABV: 3.5, Image: "beer_images/xxxx-gold-mid-strength-lager-bottles-375ml.png"},
		{ID: "315-wild-yak-pacific-ale", Name: "Wild Yak Pacific Ale", Brewery: "Yak Brewing", ABV: 4.2, Image: "beer_images/yak-brewing-wild-yak-pacific-ale-bottles-345ml.png"},
		{ID: "316-newtowner-australian-pale-ale", Name: "Newtowner Australian Pale Ale", Brewery: "Young Henrys", ABV: 4.8, Image: "beer_images/young-henrys-newtowner-australian-pale-ale-cans-375ml.png"},
		{ID: "317-japanese-lager", Name: "Japanese Lager", Brewery: "4 Pines", ABV: 4.5, Image: "beer_images/4-pines-japanese-lager-cans-375ml.png"},
		{ID: "318-new-world-pale-ale", Name: "New World Pale Ale", Brewery: "4 Pines", ABV: 4.2, Image: "beer_images/4-pines-new-world-pale-ale-can-375ml.png"},
		{ID: "319-pacific-ale", Name: "Pacific Ale", Brewery: "4 Pines", ABV: 3.5, Image: "beer_images/4-pines-pacific-ale-bottles-330ml.png"},
		{ID: "320-pale-ale", Name: "Pale Ale", Brewery: "4 Pines", ABV: 5.1, Image: "beer_images/4-pines-pale-ale-can-375ml.png"},
		{ID: "321-super-dry-fusions-lemon-yuzu", Name: "Super Dry Fusions Lemon Yuzu", Brewery: "Asahi", ABV: 4.0, Image: "beer_images/asahi-super-dry-fusions-lemon-yuzu-bottle-330ml.png"},
		{ID: "322-hawaiian-haze-pale-ale", Name: "Hawaiian Haze Pale Ale", Brewery: "Ballistic", ABV: 4.6, Image: "beer_images/ballistic-hawaiian-haze-pale-ale-cans-375ml.png"},
		{ID: "323-captain-sensible", Name: "Captain Sensible", Brewery: "Balter", ABV: 3.5, Image: "beer_images/balter-captain-sensible-cans-375ml.png"},
		{ID: "324-eazy-hazy", Name: "Eazy Hazy", Brewery: "Balter", ABV: 4.0, Image: "beer_images/balter-eazy-hazy-cans-375ml.png"},
		{ID: "325-ipa", Name: "Ipa", Brewery: "Balter", ABV: 6.8, Image: "beer_images/balter-ipa-cans-375ml.png"},
		{ID: "326-beer-lager", Name: "Beer Lager", Brewery: "Bear", ABV: 5.0, Image: "beer_images/beck-s-beer-330ml.png"},
		{ID: "327-manuka-honey-sparkling-mead", Name: "Manuka Honey Sparkling Mead", Brewery: "Beemead", ABV: 4.5, Image: "beer_images/beemead-manuka-honey-sparkling-mead-500ml.png"},
		{ID: "328-crankshaft-ipa", Name: "Crankshaft Ipa", Brewery: "BentSpoke Brewing Co.", ABV: 5.8, Image: "beer_images/bentspoke-brewing-co-crankshaft-ipa-cans-375ml.png"},
		{ID: "329-zero-alcohol", Name: "Zero Alcohol", Brewery: "Better Beer", ABV: 0.0, Image: "beer_images/better-beer-zero-alcohol-cans-355ml.png"},
		{ID: "330-premium-beer", Name: "Premium Beer", Brewery: "Bitburger", ABV: 4.8, Image: "beer_images/bitburger-premium-beer-330ml.png"},
		{ID: "331-affinity-pale-ale", Name: "Affinity Pale Ale", Brewery: "Blackflag Brewing", ABV: 4.7, Image: "beer_images/blackflag-brewing-affinity-pale-ale-cans-375ml.png"},
		{ID: "332-full-strength-lager", Name: "Full Strength Lager", Brewery: "Bluey", ABV: 4.2, Image: "beer_images/bluey-full-strength-lager-can-375ml.png"},
		{ID: "333-ultra-crisp-lager", Name: "Ultra Crisp Lager", Brewery: "Bluey", ABV: 3.5, Image: "beer_images/bluey-ultra-crisp-lager-cans-375ml.png"},
		{ID: "334-beechworth-pale-ale", Name: "Beechworth Pale Ale", Brewery: "Bridge Road Brewers", ABV: 4.8, Image: "beer_images/bridge-road-brewers-beechworth-pale-ale-bottles-330ml.png"},
		{ID: "335-28-pale-ale", Name: "28 Pale Ale", Brewery: "Burleigh Brewing Co.", ABV: 4.8, Image: "beer_images/burleigh-brewing-co-28-pale-ale-330ml.png"},
		{ID: "336-fruit-lager-passionfruit-mango", Name: "Fruit Lager Passionfruit Mango", Brewery: "Byron Bay Brewery", ABV: 4.0, Image: "beer_images/byron-bay-brewery-fruit-lager-passionfruit-mango-355ml.png"},
		{ID: "337-cerveza-lager", Name: "Cerveza Lager", Brewery: "Calaverita", ABV: 4.4, Image: "beer_images/calaverita-cerveza-lager-bottles-355ml.png"},
		{ID: "338-green-lager", Name: "Green Lager", Brewery: "Carlsberg", ABV: 4.8, Image: "beer_images/carlsberg-green-lager-bottles-330ml.png"},
		{ID: "339-cold", Name: "Cold", Brewery: "Carlton", ABV: 3.5, Image: "beer_images/carlton-cold-bottles.png"},
		{ID: "340-", Name: "", Brewery: "Carlton Dry", ABV: 4.5, Image: "beer_images/carlton-mid-750ml.png"},
		{ID: "341-zero-non-alcoholic-beer", Name: "Zero Non Alcoholic Beer", Brewery: "Carlton", ABV: 0.0, Image: "beer_images/carlton-zero-non-alcoholic-beer-bottles-330ml.png"},
		{ID: "342-ipa", Name: "Ipa", Brewery: "CBCo Brewing", ABV: 6.5, Image: "beer_images/cbco-brewing-ipa-cans-375ml.png"},
		{ID: "343-beer", Name: "Beer", Brewery: "Chang", ABV: 5.0, Image: "beer_images/chang-beer.png"},
		{ID: "344-ipa", Name: "Ipa", Brewery: "Colonial Brewing Co", ABV: 6.5, Image: "beer_images/colonial-brewing-co-ipa-cans-375ml.png"},
		{ID: "345-southwest-sour", Name: "Southwest Sour", Brewery: "Colonial Brewing Co", ABV: 4.6, Image: "beer_images/colonial-brewing-co-southwest-sour-cans-375ml.png"},
		{ID: "346-mind-harvest-east-coast-ipa", Name: "Mind Harvest East Coast Ipa", Brewery: "Colossal Brewing", ABV: 6.0, Image: "beer_images/colossal-brewing-mind-harvest-east-coast-ipa-cans-375ml.png"},
		{ID: "347-dark-ale", Name: "Dark Ale", Brewery: "Coopers", ABV: 4.5, Image: "beer_images/coopers-dark-ale-bottles-375ml.png"},
		{ID: "348-dry-3.5-lager", Name: "Dry 3.5 Lager", Brewery: "Coopers", ABV: 3.5, Image: "beer_images/coopers-dry-3-5-lager-cans-375ml.png"},
		{ID: "349-pacific-pale-ale", Name: "Pacific Pale Ale", Brewery: "Coopers", ABV: 4.2, Image: "beer_images/coopers-pacific-pale-ale-cans-375ml.png"},
		{ID: "350-premium-lager", Name: "Premium Lager", Brewery: "Coopers", ABV: 4.8, Image: "beer_images/coopers-premium-lager-355ml.png"},
		{ID: "351-lager", Name: "Lager", Brewery: "Coors", ABV: 4.2, Image: "beer_images/coors-lager-cans-355ml.png"},
		{ID: "352-pale-ale", Name: "Pale Ale", Brewery: "Cricketers Arms", ABV: 4.6, Image: "beer_images/cricketers-arms-pale-ale-cans-375ml.png"},
		{ID: "353-scorcher-summer-ale", Name: "Scorcher Summer Ale", Brewery: "Cricketers Arms", ABV: 4.6, Image: "beer_images/cricketers-arms-scorcher-summer-ale-330ml.png"},
		{ID: "354-session-ale", Name: "Session Ale", Brewery: "Cricketers Arms", ABV: 3.5, Image: "beer_images/cricketers-arms-session-ale-cans-375ml.png"},
		{ID: "355-summer-ale", Name: "Summer Ale", Brewery: "Cricketers", ABV: 4.6, Image: "beer_images/cricketers-summer-ale-330ml.png"},
		{ID: "356-raspberry-berliner-weisse-beer", Name: "Raspberry Berliner Weisse Beer", Brewery: "Culture House", ABV: 3.5, Image: "beer_images/culture-house-raspberry-berliner-weisse-bier-375ml.png"},
		{ID: "357-german-beer", Name: "German Beer", Brewery: "Dab", ABV: 5.0, Image: "beer_images/dab-german-beer-cans-500ml.png"},
		{ID: "358-lager-especial", Name: "Lager Especial", Brewery: "Dos Equis", ABV: 4.2, Image: "beer_images/dos-equis-lager-especial-355ml.png"},
		{ID: "359-pale-lager", Name: "Pale Lager", Brewery: "Doss Blockos", ABV: 4.6, Image: "beer_images/doss-blockos-pale-lager.png"},
		{ID: "360-lager", Name: "Lager", Brewery: "Estrella Damm", ABV: 4.6, Image: "beer_images/estrella-damm-lager-330ml.png"},
		{ID: "361-outback-lager", Name: "Outback Lager", Brewery: "First Hand Beer", ABV: 4.2, Image: "beer_images/first-hand-beer-outback-lager-cans-375ml.png"},
		{ID: "362-sacred-lager-mid", Name: "Sacred Lager Mid", Brewery: "First Hand Beer", ABV: 3.5, Image: "beer_images/first-hand-beer-sacred-lager-mid-cans-375ml.png"},
		{ID: "363-classic-lager", Name: "Classic Lager", Brewery: "Foster's", ABV: 4.0, Image: "beer_images/foster-s-classic-lager-cans-375ml.png"},
		{ID: "364-light-ice", Name: "Light Ice", Brewery: "Foster's", ABV: 2.0, Image: "beer_images/foster-s-light-ice-bottle-330ml.png"},
		{ID: "365-little-dove-new-world-pale-ale", Name: "Little Dove New World Pale Ale", Brewery: "Gage Roads", ABV: 6.2, Image: "beer_images/gage-roads-little-dove-new-world-pale-ale-330ml.png"},
		{ID: "366-single-fin-summer-ale", Name: "Single Fin Summer Ale", Brewery: "Gage Roads", ABV: 4.5, Image: "beer_images/gage-roads-single-fin-summer-ale-cans-330ml.png"},
		{ID: "367-zero-alcohol-lager", Name: "Zero Alcohol Lager", Brewery: "Good Form", ABV: 0.5, Image: "beer_images/good-form-zero-alcohol-lager-bottle-330ml.png"},
		{ID: "368-light", Name: "Light", Brewery: "Great Northern Brewing Co.", ABV: 2.0, Image: "beer_images/great-northern-brewing-co-light-bottle-330ml.png"},
		{ID: "369-long-run", Name: "Long Run", Brewery: "Great Northern Brewing Co.", ABV: 4.5, Image: "beer_images/great-northern-brewing-co-long-run-bottles-330ml.png"},
		{ID: "370-3-bolt-pale-ale", Name: "3 Bolt Pale Ale", Brewery: "Green Beacon", ABV: 4.5, Image: "beer_images/green-beacon-brewing-co-3-bolt-pale-ale.png"},
		{ID: "371-7-bells-passion-fruit-sour", Name: "7 Bells Passion Fruit Sour", Brewery: "Green Beacon", ABV: 4.2, Image: "beer_images/green-beacon-7-bells-passion-fruit-sour-375ml.png"},
		{ID: "372-american-style-premium-lager", Name: "American Style Premium Lager", Brewery: "Green Beacon", ABV: 4.5, Image: "beer_images/green-beacon-american-style-premium-lager-cans-375ml.png"},
		{ID: "373-subtropic-low-carb-hazy-pale", Name: "Subtropic Low Carb Hazy Pale", Brewery: "Green Beacon", ABV: 4.0, Image: "beer_images/green-beacon-subtropic-low-carb-hazy-pale-can-375ml.png"},
		{ID: "374-wayfarer-tropical-pale-ale", Name: "Wayfarer Tropical Pale Ale", Brewery: "Green Beacon", ABV: 4.9, Image: "beer_images/green-beacon-wayfarer-tropical-pale-ale-cans-375ml.png"},
		{ID: "375-windjammer-ipa", Name: "Windjammer Ipa", Brewery: "Green Beacon", ABV: 6.0, Image: "beer_images/green-beacon-windjammer-ipa-cans-375ml.png"},
		{ID: "376-draught", Name: "Draught", Brewery: "Guinness", ABV: 4.2, Image: "beer_images/guinness-draught-cans-470ml.png"},
		{ID: "377-extra-stout", Name: "Extra Stout", Brewery: "Guinness", ABV: 6.0, Image: "beer_images/guinness-extra-stout-750ml.png"},
		{ID: "378-super-dry-bottle", Name: "Super Dry Bottle", Brewery: "Hahn", ABV: 4.6, Image: "beer_images/hahn-super-dry-700ml-bottle.png"},
		{ID: "379-light-beer", Name: "Light Beer", Brewery: "Halcon", ABV: 3.8, Image: "beer_images/halcon-light-beer-bottle-350ml.png"},
		{ID: "380-baltic-porter", Name: "Baltic Porter", Brewery: "Heads Of Noosa", ABV: 7.0, Image: "beer_images/heads-of-noosa-baltic-porter-bottles-330ml.png"},
		{ID: "381-lager-3.5-4x6x330ml", Name: "Lager 3.5 4x6x330ml", Brewery: "Heads Of Noosa", ABV: 3.5, Image: "beer_images/heads-of-noosa-lager-3-5-4x6x330ml.png"},
		{ID: "382-silver", Name: "Silver", Brewery: "Heineken", ABV: 4.0, Image: "beer_images/heineken-silver-bottles-330ml.png"},
		{ID: "383-cyclops-ipa", Name: "Cyclops Ipa", Brewery: "Helios", ABV: 6.0, Image: "beer_images/helios-cyclops-ipa-cans-375ml.png"},
		{ID: "384-zero-alcohol-xpa", Name: "Zero Alcohol Xpa", Brewery: "Hey Days", ABV: 0.5, Image: "beer_images/hey-days-zero-alcohol-xpa-cans-375ml.png"},
		{ID: "385-wheat-beer", Name: "Wheat Beer", Brewery: "Hoegaarden", ABV: 4.9, Image: "beer_images/hoegaarden-white-beer.png"},
		{ID: "386-pale-lager", Name: "Pale Lager", Brewery: "Hughie", ABV: 4.4, Image: "beer_images/hughie-pale-lager-cans-375ml.png"},
		{ID: "387-brewing-co-lager", Name: "Brewing Co Lager", Brewery: "Hurricane Head", ABV: 4.2, Image: "beer_images/hurricane-head-brewing-co-lager-bottle-330ml.png"},
		{ID: "388-lager", Name: "Lager", Brewery: "Hurricane Head", ABV: 4.2, Image: "beer_images/hurricane-head-lager-cans-375ml.png"},
		{ID: "389-ipa", Name: "Ipa", Brewery: "Initial Brewing", ABV: 4.5, Image: "beer_images/initial-brewing-ipa-can-375ml.png"},
		{ID: "390-lager", Name: "Lager", Brewery: "Isbjorn", ABV: 4.5, Image: "beer_images/isbjorn-lager-330ml.png"},
		{ID: "391-draught", Name: "Draught", Brewery: "James Boag's", ABV: 5.5, Image: "beer_images/james-boag-s-draught-bottle-750ml.png"},
		{ID: "392-premium-light", Name: "Premium Light", Brewery: "James Boag's", ABV: 2.3, Image: "beer_images/james-boag-s-premium-light-bottles-375ml.png"},
		{ID: "393-broken-shackles-lager", Name: "Broken Shackles Lager", Brewery: "James Squire", ABV: 4.6, Image: "beer_images/james-squire-broken-shackles-lager-bottles-345ml.png"},
		{ID: "394-low-carb-pale-ale", Name: "Low Carb Pale Ale", Brewery: "James Squire", ABV: 4.2, Image: "beer_images/james-squire-low-carb-pale-ale-bottles-330ml.png"},
		{ID: "395-one-fifty-lashes-pale-ale", Name: "One Fifty Lashes Pale Ale", Brewery: "James Squire", ABV: 4.2, Image: "beer_images/james-squire-one-fifty-lashes-pale-ale-cans-10-pack-330ml.png"},
		{ID: "396-zero-alc", Name: "Zero Alc", Brewery: "James Squire", ABV: 0.0, Image: "beer_images/james-squire-zero-alc-bottle-330ml.png"},
		{ID: "397-zero-alcohol", Name: "Zero Alcohol", Brewery: "James Squire", ABV: 0.0, Image: "beer_images/james-squire-zero-alcohol-bottle-345ml.png"},
		{ID: "398-crisp-lager", Name: "Crisp Lager", Brewery: "John Boston", ABV: 4.2, Image: "beer_images/john-boston-crisp-lager-bottle-330ml.png"},
		{ID: "399-pacific-ale", Name: "Pacific Ale", Brewery: "John Boston", ABV: 4.2, Image: "beer_images/john-boston-pacific-ale-bottle-330ml.png"},
		{ID: "400-pale-ale", Name: "Pale Ale", Brewery: "John Boston", ABV: 4.2, Image: "beer_images/john-boston-xpa-can-375ml.png"},
		{ID: "401-session-ipa", Name: "Session Ipa", Brewery: "John Boston", ABV: 4.2, Image: "beer_images/john-boston-session-ipa-330ml.png"},
		{ID: "402-the-guardhouse-golden-ale", Name: "The Guardhouse Golden Ale", Brewery: "John Boston", ABV: 4.2, Image: "beer_images/john-boston-the-guardhouse-golden-ale-330ml.png"},
		{ID: "403-xpa", Name: "Xpa", Brewery: "John Boston", ABV: 4.2, Image: "beer_images/john-boston-xpa-can-375ml.png"},
		{ID: "404-irish-ale", Name: "Irish Ale", Brewery: "Kilkenny", ABV: 4.3, Image: "beer_images/kilkenny-irish-ale-cans-470ml.png"},
		{ID: "405-hyoketsu-lemon-10-pack", Name: "Hyoketsu Lemon 10 Pack", Brewery: "Kirin", ABV: 6.0, Image: "beer_images/kirin-hyoketsu-lemon-10-pack-cans-330ml.png"},
		{ID: "406-ichiban", Name: "Ichiban", Brewery: "Kirin", ABV: 5.0, Image: "beer_images/kirin-ichiban-bottle-330ml.png"},
		{ID: "407-variety-pack", Name: "Variety Pack", Brewery: "Kirin", ABV: 6.0, Image: "beer_images/kirin-variety-pack-cans-10x330ml.png"},
		{ID: "408-fruitz-hard-lemon", Name: "Fruitz Hard Lemon", Brewery: "Kopparberg", ABV: 8.3, Image: "beer_images/kopparberg-fruitz-hard-lemon-8-3-375ml.png"},
		{ID: "409-fruitz-hard-pineapple", Name: "Fruitz Hard Pineapple", Brewery: "Kopparberg", ABV: 8.3, Image: "beer_images/kopparberg-fruitz-hard-pineapple-8-3-375ml.png"},
		{ID: "410-clean-lager", Name: "Clean Lager", Brewery: "Largo", ABV: 4.2, Image: "beer_images/largo-clean-lager-cans-375ml.png"},
		{ID: "411-australian-lager", Name: "Australian Lager", Brewery: "Last Man Standing", ABV: 4.5, Image: "beer_images/last-man-standing-australian-lager-cans-375ml.png"},
		{ID: "412-little-hazy-lager", Name: "Little Hazy Lager", Brewery: "Little Creatures", ABV: 3.5, Image: "beer_images/little-creatures-little-hazy-lager-cans-375ml.png"},
		{ID: "413-rogers-ale", Name: "Rogers Ale", Brewery: "Little Creatures", ABV: 3.8, Image: "beer_images/little-creatures-rogers-ale-bottle-330ml.png"},
		{ID: "414-xpa", Name: "Xpa", Brewery: "Little Creatures", ABV: 4.9, Image: "beer_images/little-creatures-xpa-330ml.png"},
		{ID: "415-brewed-berry", Name: "Brewed Berry", Brewery: "Little Fat Lamb", ABV: 8.0, Image: "beer_images/little-fat-lamb-brewed-berry.png"},
		{ID: "416-brewed-strawberry-&-lime", Name: "Brewed Strawberry & Lime", Brewery: "Little Fat Lamb", ABV: 8.0, Image: "beer_images/little-fat-lamb-brewed-berry.png"},
		{ID: "417-salted-caramel-cream-liqueur", Name: "Salted Caramel Cream Liqueur", Brewery: "Little Fat Lamb", ABV: 13.9, Image: "beer_images/little-fat-lamb-salted-caramel-cream-liqueur-700ml.png"},
		{ID: "418-buddha-beer", Name: "Buddha Beer", Brewery: "Lucky", ABV: 4.8, Image: "beer_images/lucky-buddha-beer-bottles-330ml.png"},
		{ID: "419-japanese-style-lager", Name: "Japanese Style Lager", Brewery: "Matso's", ABV: 4.5, Image: "beer_images/matso-s-japanese-style-lager-bottles-330ml.png"},
		{ID: "420-mango-beer", Name: "Mango Beer", Brewery: "Matso's", ABV: 4.5, Image: "beer_images/matso-s-mango-beer-330ml.png"},
		{ID: "421-genuine-draft", Name: "Genuine Draft", Brewery: "Miller", ABV: 4.7, Image: "beer_images/miller-genuine-draft-330ml.png"},
		{ID: "422-cerveza", Name: "Cerveza", Brewery: "Modus", ABV: 4.2, Image: "beer_images/modus-cerveza-bottles-330ml.png"},
		{ID: "423-green-apple-chuhai", Name: "Green Apple Chuhai", Brewery: "Monsuta", ABV: 7.3, Image: "beer_images/monsuta-green-apple-chuhai-7-3-can-350ml.png"},
		{ID: "424-okinawa-dark-premium-lager", Name: "Okinawa Dark Premium Lager", Brewery: "Monsuta", ABV: 5.0, Image: "beer_images/monsuta-okinawa-dark-premium-lager-can-350ml.png"},
		{ID: "425-okinawa-supreme-lager", Name: "Okinawa Supreme Lager", Brewery: "Monsuta", ABV: 5.0, Image: "beer_images/monsuta-okinawa-supreme-lager-cans-350ml.png"},
		{ID: "426-vodka-chuhai-7.3pct", Name: "Vodka Chuhai 7.3pct", Brewery: "Monsuta", ABV: 7.3, Image: "beer_images/monsuta-vodka-chuhai-7-3pct-cans-10x350ml.png"},
		{ID: "427-blueberry-fruity-beer", Name: "Blueberry Fruity Beer", Brewery: "Mosey", ABV: 4.2, Image: "beer_images/mosey-blueberry-fruity-beer-300ml.png"},
		{ID: "428-garage-project-majestic-haze-ipa", Name: "Garage Project Majestic Haze Ipa", Brewery: "Mountain Culture", ABV: 6.0, Image: "beer_images/mountain-culture-garage-project-majestic-haze-ipa-cans-355ml.png"},
		{ID: "429-low-carb-lager", Name: "Low Carb Lager", Brewery: "Mountain Goat", ABV: 4.0, Image: "beer_images/mountain-goat-low-carb-lager-can-375ml.png"},
		{ID: "430-summer-ale", Name: "Summer Ale", Brewery: "Mountain Goat", ABV: 4.7, Image: "beer_images/mountain-goat-summer-ale-cans-375ml.png"},
		{ID: "431-tasty-pale-ale", Name: "Tasty Pale Ale", Brewery: "Mountain Goat", ABV: 4.4, Image: "beer_images/mountain-goat-tasty-pale-ale-can-375ml.png"},
		{ID: "432-lager", Name: "Lager", Brewery: "Nam Nam Alley", ABV: 4.5, Image: "beer_images/nam-nam-alley-lager-can-500ml.png"},
		{ID: "433-pale-ale", Name: "Pale Ale", Brewery: "New Dawn Brewing", ABV: 4.5, Image: "beer_images/new-dawn-brewing-pale-ale-can-375ml.png"},
		{ID: "434-session-ale", Name: "Session Ale", Brewery: "Newstead Brewing Co.", ABV: 3.4, Image: "beer_images/newstead-brewing-co-session-ale-cans-375ml.png"},
		{ID: "435-non-alcoholic-refreshing-ale", Name: "Non Alcoholic Refreshing Ale", Brewery: "Nort", ABV: 0.0, Image: "beer_images/nort-non-alcoholic-refreshing-ale-bottle-330ml.png"},
		{ID: "436-premium-lager", Name: "Premium Lager", Brewery: "Pabst Blue Ribbon", ABV: 4.7, Image: "beer_images/pabst-blue-ribbon-premium-lager-cans-473ml.png"},
		{ID: "437-ipa", Name: "Ipa", Brewery: "Philter", ABV: 7.7, Image: "beer_images/philter-ipa-375ml.png"},
		{ID: "438-xpa", Name: "Xpa", Brewery: "Philter", ABV: 4.2, Image: "beer_images/philter-ipa-375ml.png"},
		{ID: "439-ultra-smooth-lager", Name: "Ultra Smooth Lager", Brewery: "Powers", ABV: 4.0, Image: "beer_images/powers-ultra-smooth-lager-bottles-330ml.png"},
		{ID: "440-premium-mid-ultra-low-carb-lager", Name: "Premium Mid Ultra Low Carb Lager", Brewery: "Pure Blonde", ABV: 3.0, Image: "beer_images/pure-blonde-premium-mid-ultra-low-carb-355ml.png"},
		{ID: "441-premium-strawberry-&-lime-low-sugar", Name: "Premium Strawberry & Lime Low Sugar", Brewery: "Rekorderlig", ABV: 4.0, Image: "beer_images/rekorderlig-premium-strawberry-lime-low-sugar-330ml.png"},
		{ID: "442-pale-ale", Name: "Pale Ale", Brewery: "Sail & Anchor", ABV: 4.2, Image: "beer_images/sail-anchor-pale-ale-bottles-330ml.png"},
		{ID: "443-crisp-lager", Name: "Crisp Lager", Brewery: "Sneaky Bucha", ABV: 4.0, Image: "beer_images/sneaky-bucha-crisp-lager-bottle-330ml.png"},
		{ID: "444-crisp-lager-and-kombucha", Name: "Crisp Lager And Kombucha", Brewery: "Sneaky Bucha of Byron", ABV: 4.0, Image: "beer_images/sneaky-bucha-of-byron-crisp-lager-and-kombucha-330ml.png"},
		{ID: "445-blonde", Name: "Blonde", Brewery: "Steersman", ABV: 4.2, Image: "beer_images/steersman-blonde-4-2-cans-330ml.png"},
		{ID: "446-lime-lager", Name: "Lime Lager", Brewery: "Steersman", ABV: 4.0, Image: "beer_images/steersman-lime-lager-bottles-330ml.png"},
		{ID: "447-ultra-crisp-beer", Name: "Ultra Crisp Beer", Brewery: "Steersman", ABV: 3.5, Image: "beer_images/steersman-ultra-crisp-beer-330ml.png"},
		{ID: "448-ultra-mid", Name: "Ultra Mid", Brewery: "Steersman", ABV: 3.5, Image: "beer_images/steersman-ultra-mid-bottle-330ml.png"},
		{ID: "449-pure-beer", Name: "Pure Beer", Brewery: "Steinlager", ABV: 5.0, Image: "beer_images/steinlager-pure-beer-bottles.png"},
		{ID: "450-cloudy-pale-ale", Name: "Cloudy Pale Ale", Brewery: "Stone & Wood", ABV: 5.0, Image: "beer_images/stone-wood-cloudy-pale-ale-cans-375ml.png"},
		{ID: "451-hinterland-big-pale-ale", Name: "Hinterland Big Pale Ale", Brewery: "Stone & Wood", ABV: 5.6, Image: "beer_images/stone-wood-hinterland-big-pale-ale-can-375ml.png"},
		{ID: "452-radler-citrus", Name: "Radler Citrus", Brewery: "Stone & Wood", ABV: 4.0, Image: "beer_images/stone-wood-radler-citrus-cans-330ml.png"},
		{ID: "453-pineapple-&-passionfruit-seltzer", Name: "Pineapple & Passionfruit Seltzer", Brewery: "Strongbow", ABV: 4.5, Image: "beer_images/strongbow-pineapple-passionfruit-seltzer-can-330ml.png"},
		{ID: "454-raspberry-and-pomegranate-seltzer", Name: "Raspberry And Pomegranate Seltzer", Brewery: "Strongbow", ABV: 4.2, Image: "beer_images/strongbow-raspberry-and-pomegranate-seltzer-cans-330ml.png"},
		{ID: "455-lager", Name: "Lager", Brewery: "Sudo", ABV: 5.0, Image: "beer_images/sudo-lager-can-350ml.png"},
		{ID: "456-asian-lager", Name: "Asian Lager", Brewery: "Tiger", ABV: 5.0, Image: "beer_images/tiger-asian-lager-bottles-640ml.png"},
		{ID: "457-full-strength-lager", Name: "Full Strength Lager", Brewery: "Travla", ABV: 4.2, Image: "beer_images/travla-full-strength-lager-cans-375ml.png"},
		{ID: "458-mid-strength-lager", Name: "Mid Strength Lager", Brewery: "Travla", ABV: 3.5, Image: "beer_images/travla-mid-strength-lager-cans-375ml.png"},
		{ID: "459-lager", Name: "Lager", Brewery: "Trost", ABV: 4.7, Image: "beer_images/trost-lager-can-330ml.png"},
		{ID: "460-premium-lager", Name: "Premium Lager", Brewery: "Tsingtao", ABV: 4.5, Image: "beer_images/tsingtao-premium-lager-bottles-330ml.png"},
		{ID: "461-bitter", Name: "Bitter", Brewery: "Tun", ABV: 4.9, Image: "beer_images/tun-bitter-bottle-660ml.png"},
		{ID: "462-low-carb", Name: "Low Carb", Brewery: "Victoria Bitter", ABV: 4.9, Image: "beer_images/victoria-bitter-low-carb-bottle-375ml.png"},
		{ID: "463-twist-tops", Name: "Twist Tops", Brewery: "Victoria Bitter", ABV: 4.9, Image: "beer_images/victoria-bitter-twist-tops-250ml.png"},
		{ID: "464-malaga-lager", Name: "Malaga Lager", Brewery: "Victoria Malaga", ABV: 4.8, Image: "beer_images/victoria-malaga-malaga-lager-cans-330ml.png"},
		{ID: "465-premium-lager", Name: "Premium Lager", Brewery: "Wakachangi", ABV: 5.0, Image: "beer_images/wakachangi-premium-lager-cans-330ml.png"},
		{ID: "466-original", Name: "Original", Brewery: "West Coast", ABV: 3.5, Image: "beer_images/west-coast-original-250ml.png"},
		{ID: "467-dark-ale", Name: "Dark Ale", Brewery: "White Rabbit", ABV: 4.9, Image: "beer_images/white-rabbit-dark-ale-330ml.png"},
		{ID: "468-bitter", Name: "Bitter", Brewery: "XXXX", ABV: 4.6, Image: "beer_images/xxxx-bitter-cans.png"},
		{ID: "469-bitter", Name: "Bitter", Brewery: "XXXX Bitter", ABV: 4.4, Image: "beer_images/xxxx-bitter-bitter-cans-375ml.png"},
		{ID: "470-bright-lager-with-mango", Name: "Bright Lager With Mango", Brewery: "XXXX", ABV: 4.0, Image: "beer_images/xxxx-bright-lager-with-mango-bottles-330ml.png"},
		{ID: "471-gold-australian-pale-ale", Name: "Gold Australian Pale Ale", Brewery: "XXXX", ABV: 3.5, Image: "beer_images/xxxx-gold-australian-pale-ale-bottles-375ml.png"},
		{ID: "472-gold-mid-strength-lager-beer-long-neck-bottle-750m", Name: "Gold Mid Strength Lager Beer Long Neck Bottle 750m", Brewery: "XXXX", ABV: 3.5, Image: "beer_images/xxxx-gold-mid-strength-lager-beer-long-neck-bottle-750m.png"},
		{ID: "473-summer-bright-lager", Name: "Summer Bright Lager", Brewery: "XXXX", ABV: 4.0, Image: "beer_images/xxxx-summer-bright-lager-cans-375ml.png"},
		{ID: "474-summer-bright-lager-raspberry-lemonade-bottle-330m", Name: "Summer Bright Lager Raspberry Lemonade Bottle 330m", Brewery: "XXXX", ABV: 4.0, Image: "beer_images/xxxx-summer-bright-lager-raspberry-lemonade-bottle-330m.png"},
		{ID: "475-ultra-zero-carb", Name: "Ultra Zero Carb", Brewery: "XXXX", ABV: 3.8, Image: "beer_images/xxxx-ultra-zero-carb-cans-375ml.png"},
		{ID: "476-pale-ale", Name: "Pale Ale", Brewery: "Yenda", ABV: 4.5, Image: "beer_images/yenda-pale-ale-330ml.png"},
		{ID: "477-classic-crisp-mid", Name: "Classic Crisp Mid", Brewery: "Young Henrys", ABV: 3.5, Image: "beer_images/young-henrys-classic-crisp-mid-can-375ml.png"},
		{ID: "478-classic-premium-lager", Name: "Classic Premium Lager", Brewery: "Young Henrys", ABV: 4.2, Image: "beer_images/young-henrys-classic-premium-lager-can-375ml.png"},
		{ID: "479-hazy-pale-ale", Name: "Hazy Pale Ale", Brewery: "Young Henrys", ABV: 5.2, Image: "beer_images/young-henrys-hazy-pale-ale-375ml.png"},
		{ID: "480-larry-pale-ale", Name: "Larry Pale Ale", Brewery: "Your Mates Brewing Co.", ABV: 4.5, Image: "beer_images/your-mates-brewing-co-larry-pale-ale-375ml.png"},
		{ID: "481-low-carb-lager", Name: "Low Carb Lager", Brewery: "Your Mates Brewing Co.", ABV: 4.2, Image: "beer_images/your-mates-brewing-co-low-carb-lager-cans-355ml.png"},
		{ID: "482-sally-ipa", Name: "Sally Ipa", Brewery: "Your Mates Brewing Co.", ABV: 6.0, Image: "beer_images/your-mates-brewing-co-sally-ipa-can-375ml.png"},
		{ID: "483-jed-mid-strength", Name: "Jed Mid Strength", Brewery: "Yulli's Brews", ABV: 3.5, Image: "beer_images/yulli-s-brews-jed-mid-strength-can-375ml.png"},
		{ID: "484-ipa", Name: "Ipa", Brewery: "Zytho Brewing", ABV: 5.4, Image: "beer_images/zytho-brewing-ipa-cans-375ml.png"},
		{ID: "485-tropical-haze", Name: "Tropical Haze", Brewery: "Zytho Brewing", ABV: 5.0, Image: "beer_images/zytho-brewing-tropical-haze-cans-375ml.png"},
		{ID: "486-velvet-luxe-stout", Name: "Velvet Luxe Stout", Brewery: "Zytho Brewing", ABV: 6.0, Image: "beer_images/zytho-brewing-velvet-luxe-stout-cans-375ml.png"},
		{ID: "487-zesty-pale-ale", Name: "Zesty Pale Ale", Brewery: "Zytho Brewing", ABV: 4.6, Image: "beer_images/zytho-brewing-zesty-pale-ale-cans-375ml.png"},
		{ID: "492-pale-ale", Name: "Pale Ale", Brewery: "Black Hops", ABV: 4.8, Image: ""},
		{ID: "493-burrow-pale-ale", Name: "burrow pale ale", Brewery: "Slipstream", ABV: 4.2, Image: ""},
		{ID: "494-ipa", Name: "IPA", Brewery: "Brouhaha", ABV: 6.2, Image: ""},
		{ID: "495-some-random-beer-at-brew", Name: "some random beer at brew", Brewery: "idk", ABV: 4.2, Image: ""},
	}

	for _, b := range beers {
		item := CatalogueItem{
			PK:      "CATALOGUE",
			SK:      fmt.Sprintf("BEER#%s", b.ID),
			GSI1PK:  "CATALOGUE",
			GSI1SK:  fmt.Sprintf("%s#%s", b.Brewery, b.Name),
			BeerID:  b.ID,
			Name:    b.Name,
			Brewery: b.Brewery,
			ABV:     b.ABV,
			Image:   b.Image,
		}

		av, _ := attributevalue.MarshalMap(item)
		_, err := db.PutItem(context.Background(), &dynamodb.PutItemInput{
			TableName: beerAws.TableName(),
			Item:      av,
		})
		if err != nil {
			log.Printf("Error inserting %s: %v", b.Name, err)
		}
	}
	log.Println("Seed complete!")
}
