package main

import (
	"context"
	"fmt"
	"log"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	beerAws "github.com/tristanbatchler/itsbeeroclock/backend/internal/aws"
	"github.com/tristanbatchler/itsbeeroclock/backend/internal/models"
)

type CatalogueItem struct {
	PK      string  `dynamodbav:"PK"`     // CATALOGUE
	SK      string  `dynamodbav:"SK"`     // BEER#{id}
	GSI1PK  string  `dynamodbav:"GSI1PK"` // CATALOGUE
	GSI1SK  string  `dynamodbav:"GSI1SK"` // {brewery}#{name}
	BeerID  string  `dynamodbav:"BeerID"`
	Name    string  `dynamodbav:"Name"`
	Brewery string  `dynamodbav:"Brewery"`
	ABV     float64 `dynamodbav:"ABV"`
}

func main() {
	cfg, err := config.LoadDefaultConfig(context.Background(), config.WithRegion("ap-southeast-2"))
	if err != nil {
		log.Fatal(err)
	}
	db := dynamodb.NewFromConfig(cfg)

	beers := []models.Beer{
		{ID: "1-pacific-ale", Name: "Pacific Ale", Brewery: "Stone & Wood", ABV: 4.4},
		{ID: "2-hazy-pale-ale", Name: "Hazy Pale Ale", Brewery: "Range Brewing", ABV: 5.2},
		{ID: "3-pale-ale", Name: "Pale Ale", Brewery: "Coopers Brewery", ABV: 4.5},
		{ID: "4-zero-carb", Name: "Zero Carb", Brewery: "Better Beer", ABV: 4.2},
		{ID: "5-ginger-beer", Name: "Ginger Beer", Brewery: "Better Beer", ABV: 4.0},
		{ID: "6-zero-alc", Name: "Zero Alc", Brewery: "Better Beer", ABV: 0.0},
		{ID: "7-1857-bitter", Name: "1857 Bitter", Brewery: "Swan Brewery", ABV: 3.5},
		{ID: "8-1857-pilsener", Name: "1857 Pilsener", Brewery: "Swan Brewery", ABV: 4.8},
		{ID: "9-303-icegold", Name: "303 Icegold", Brewery: "Carlton and United", ABV: 3.3},
		{ID: "10-abbotsford-invalid-stout", Name: "Abbotsford Invalid Stout", Brewery: "Carlton and United", ABV: 5.6},
		{ID: "11-albany-ale", Name: "Albany Ale", Brewery: "The Rare Amber Brewing Co", ABV: 4.4},
		{ID: "12-amber-bitter", Name: "Amber Bitter", Brewery: "Toohey's", ABV: 3.5},
		{ID: "13-australian-white-beer", Name: "Australian White Beer", Brewery: "Malt Shovel Brewery", ABV: 5.0},
		{ID: "14-autumn-amber", Name: "Autumn Amber", Brewery: "Cascade", ABV: 5.0},
		{ID: "15-beamvar", Name: "Beamvar", Brewery: "Swanbourne Fermenting Co", ABV: 3.2},
		{ID: "16-beez-neez", Name: "Beez Neez", Brewery: "Gold Coast Brewery", ABV: 5.0},
		{ID: "17-beez-neez", Name: "Beez Neez", Brewery: "Matilda Bay", ABV: 4.7},
		{ID: "18-blue-tongue-premium-lager", Name: "Blue Tongue Premium Lager", Brewery: "Blue Tongue Brewery", ABV: 4.9},
		{ID: "19-boag's-bitter", Name: "Boag's Bitter", Brewery: "J. Boag & Son", ABV: 4.9},
		{ID: "20-boag's-draught", Name: "Boag's Draught", Brewery: "J. Boag & Son", ABV: 4.7},
		{ID: "21-boag's-light-draught", Name: "Boag's Light Draught", Brewery: "J. Boag & Son", ABV: 2.7},
		{ID: "22-boag's-strongarm-bitter", Name: "Boag's Strongarm Bitter", Brewery: "J. Boag & Son", ABV: 5.4},
		{ID: "23-boag's-xxx-ale", Name: "Boag's XXX Ale", Brewery: "J. Boag & Son", ABV: 4.8},
		{ID: "24-boags-1881-traditional-ale", Name: "Boags 1881 Traditional Ale", Brewery: "J. Boag & Son", ABV: 5.5},
		{ID: "25-bohemian-pilsner", Name: "Bohemian Pilsner", Brewery: "Carlton and United", ABV: 4.7},
		{ID: "26-bohemian-pilzner", Name: "Bohemian Pilzner", Brewery: "Matilda Bay", ABV: 4.7},
		{ID: "27-bootleg-bitter-beer", Name: "Bootleg Bitter Beer", Brewery: "Bootleg Brewery", ABV: 5.3},
		{ID: "28-bootleg-jazz-beer", Name: "Bootleg Jazz Beer", Brewery: "Bootleg Brewery", ABV: 6.9},
		{ID: "29-bootleg-light-beer", Name: "Bootleg Light Beer", Brewery: "Bootleg Brewery", ABV: 3.3},
		{ID: "30-bootleg-pilsener", Name: "Bootleg Pilsener", Brewery: "Bootleg Brewery", ABV: 4.7},
		{ID: "31-bootleg-raging-bull", Name: "Bootleg Raging Bull", Brewery: "Bootleg Brewery", ABV: 7.1},
		{ID: "32-bootleg-wheat-beer", Name: "Bootleg Wheat Beer", Brewery: "Bootleg Brewery", ABV: 4.7},
		{ID: "33-boranup-bitter", Name: "Boranup Bitter", Brewery: "Leahdale Brewery", ABV: 4.0},
		{ID: "34-brewer's-pilsener", Name: "Brewer's Pilsener", Brewery: "Grand Ridge", ABV: 4.9},
		{ID: "35-bright-ale", Name: "Bright Ale", Brewery: "Little Creatures Brewing P/L", ABV: 4.5},
		{ID: "36-buckley's", Name: "Buckley's", Brewery: "Yarra Flats Brewery", ABV: 4.5},
		{ID: "37-bullant-bitter-ale", Name: "Bullant Bitter Ale", Brewery: "Inchant Brewing Co", ABV: 5.5},
		{ID: "38-bullant-bitter-ale-light", Name: "Bullant Bitter Ale Light", Brewery: "Inchant Brewing Co", ABV: 3.5},
		{ID: "39-bundaberg-premium", Name: "Bundaberg Premium", Brewery: "Bundaberg Distilling", ABV: 5.0},
		{ID: "40-burke's-premium-hemp-filtered-ale", Name: "Burke's Premium Hemp Filtered Ale", Brewery: "Burke's Brewing Co", ABV: 4.9},
		{ID: "41-calton-d-ale", Name: "Calton D Ale", Brewery: "Carlton and United", ABV: 4.6},
		{ID: "42-cane-toad-beer", Name: "Cane Toad Beer", Brewery: "Gold Coast Brewery", ABV: 7.0},
		{ID: "43-carbine-stout", Name: "Carbine Stout", Brewery: "Castlemaine Perkins", ABV: 5.1},
		{ID: "44-carlton-black", Name: "Carlton Black", Brewery: "Carlton and United", ABV: 4.4},
		{ID: "45-carlton-cold-filtered", Name: "Carlton Cold Filtered", Brewery: "Carlton and United", ABV: 4.9},
		{ID: "46-carlton-lj-beer", Name: "Carlton LJ Beer", Brewery: "Carlton and United", ABV: 4.6},
		{ID: "47-carlton-mid-strength-bitter", Name: "Carlton Mid Strength Bitter", Brewery: "Carlton and United", ABV: 3.5},
		{ID: "48-cascade-bitter-beer", Name: "Cascade Bitter Beer", Brewery: "Cascade", ABV: 4.8},
		{ID: "49-cascade-blonde", Name: "Cascade Blonde", Brewery: "Cascade", ABV: 4.8},
		{ID: "50-cascade-draught", Name: "Cascade Draught", Brewery: "Cascade", ABV: 4.7},
		{ID: "51-cascade-export-stout", Name: "Cascade Export Stout", Brewery: "Cascade", ABV: 5.8},
		{ID: "52-cascade-light-lager", Name: "Cascade Light Lager", Brewery: "Cascade", ABV: 2.7},
		{ID: "53-cascade-pale-ale", Name: "Cascade Pale Ale", Brewery: "Cascade", ABV: 5.2},
		{ID: "54-cascade-premium-lager", Name: "Cascade Premium Lager", Brewery: "Cascade", ABV: 4.8},
		{ID: "55-cascade-premium-light", Name: "Cascade Premium Light", Brewery: "Cascade", ABV: 2.9},
		{ID: "56-cascade-special-stout", Name: "Cascade Special Stout", Brewery: "Cascade", ABV: 5.8},
		{ID: "57-cascade-spring-fest", Name: "Cascade Spring Fest", Brewery: "Cascade", ABV: 5.0},
		{ID: "58-castlemaine-special-dry", Name: "Castlemaine Special Dry", Brewery: "Castlemaine Perkins", ABV: 5.0},
		{ID: "59-castlemaine-xxxx-bitter", Name: "Castlemaine XXXX Bitter", Brewery: "Castlemaine Perkins", ABV: 4.8},
		{ID: "60-castlemaine-xxxx-light-bitter", Name: "Castlemaine XXXX Light Bitter", Brewery: "Castlemaine Perkins", ABV: 2.7},
		{ID: "61-classic-bitter", Name: "Classic Bitter", Brewery: "Tasmanian Breweries", ABV: 4.9},
		{ID: "62-classic-light", Name: "Classic Light", Brewery: "J. Boag & Son", ABV: 2.8},
		{ID: "63-colstar", Name: "Colstar", Brewery: "n Brewing Company", ABV: 0.05},
		{ID: "64-coonawarra-pale-ale", Name: "Coonawarra Pale Ale", Brewery: "Grand Ridge", ABV: 4.5},
		{ID: "65-cooper's-best-extra-stout", Name: "Cooper's Best Extra Stout", Brewery: "Cooper's", ABV: 6.8},
		{ID: "66-cooper's-black-crow", Name: "Cooper's Black Crow", Brewery: "Cooper's", ABV: 3.6},
		{ID: "67-cooper's-dark-ale", Name: "Cooper's Dark Ale", Brewery: "Cooper's", ABV: 4.5},
		{ID: "68-cooper's-db", Name: "Cooper's DB", Brewery: "Cooper's", ABV: 4.4},
		{ID: "69-cooper's-extra-strong-vintage-ale", Name: "Cooper's Extra Strong Vintage Ale", Brewery: "Cooper's", ABV: 7.1},
		{ID: "70-cooper's-light", Name: "Cooper's Light", Brewery: "Cooper's", ABV: 2.9},
		{ID: "71-cooper's-original-pale-ale", Name: "Cooper's Original Pale Ale", Brewery: "Cooper's", ABV: 4.8},
		{ID: "72-cooper's-premium-clear-ale", Name: "Cooper's Premium Clear Ale", Brewery: "Cooper's", ABV: 4.9},
		{ID: "73-cooper's-sparkling-ale", Name: "Cooper's Sparkling Ale", Brewery: "Cooper's", ABV: 5.8},
		{ID: "74-coopers-db", Name: "Coopers DB", Brewery: "Cooper's", ABV: 4.4},
		{ID: "75-crown-lager", Name: "Crown Lager", Brewery: "Carlton and United", ABV: 4.9},
		{ID: "76-d-beer", Name: "D-Beer", Brewery: "Cascade", ABV: 3.7},
		{ID: "77-dark-ice", Name: "Dark Ice", Brewery: "Hahn Brewing Co", ABV: 4.9},
		{ID: "78-diamond", Name: "Diamond", Brewery: "Carlton and United", ABV: 4.2},
		{ID: "79-dogbolter-special-dark-lager", Name: "Dogbolter Special Dark Lager", Brewery: "Matilda Bay", ABV: 5.2},
		{ID: "80-doyles-fisherman's-lager", Name: "Doyles Fisherman's Lager", Brewery: "Malt Shovel Brewery", ABV: 5.0},
		{ID: "81-empire", Name: "Empire", Brewery: "Carlton and United", ABV: 4.6},
		{ID: "82-emu-bitter", Name: "Emu Bitter", Brewery: "Swan Brewery", ABV: 4.6},
		{ID: "83-emu-draft", Name: "Emu Draft", Brewery: "Swan Brewery", ABV: 3.5},
		{ID: "84-emu-draft-bitter", Name: "Emu Draft Bitter", Brewery: "Swan Brewery", ABV: 3.5},
		{ID: "85-emu-export", Name: "Emu Export", Brewery: "Swan Brewery", ABV: 4.9},
		{ID: "86-eumundi-lager", Name: "Eumundi Lager", Brewery: "Eumundi", ABV: 4.8},
		{ID: "87-eumundi-light", Name: "Eumundi Light", Brewery: "Eumundi", ABV: 2.7},
		{ID: "88-first-harvest-ale-2002", Name: "First Harvest Ale 2002", Brewery: "Cascade", ABV: 5.5},
		{ID: "89-foster's-extra-lager", Name: "Foster's Extra Lager", Brewery: "Carlton and United", ABV: 5.5},
		{ID: "90-foster's-lager", Name: "Foster's Lager", Brewery: "Carlton and United", ABV: 4.9},
		{ID: "91-foster's-light-ice", Name: "Foster's Light Ice", Brewery: "Carlton and United", ABV: 2.7},
		{ID: "92-foster's-special-bitter", Name: "Foster's Special Bitter", Brewery: "Carlton and United", ABV: 2.8},
		{ID: "93-full-sail", Name: "Full Sail", Brewery: "Harbour Brewing Co", ABV: 4.9},
		{ID: "94-gage-roads", Name: "Gage Roads", Brewery: "Gage Roads", ABV: 4.7},
		{ID: "95-gage-roads-lager", Name: "Gage Roads Lager", Brewery: "Gage Roads", ABV: 4.7},
		{ID: "96-genuine-cold-filtered-draught", Name: "Genuine Cold-Filtered Draught", Brewery: "Cooper's", ABV: 4.5},
		{ID: "97-gippsland-gold", Name: "Gippsland Gold", Brewery: "Grand Ridge", ABV: 4.9},
		{ID: "98-golden-ale", Name: "Golden Ale", Brewery: "Malt Shovel Brewery", ABV: 4.5},
		{ID: "99-good-ale-mead", Name: "Good Ale Mead", Brewery: "Taverner's", ABV: 8.0},
		{ID: "100-governor-broome", Name: "Governor Broome", Brewery: "Broome Brewery", ABV: 5.0},
		{ID: "101-guildford-porter", Name: "Guildford Porter", Brewery: "Inchant Brewing Co", ABV: 6.0},
		{ID: "102-haagen-premium-malt", Name: "Haagen Premium Malt", Brewery: "Independent Breweries", ABV: 5.0},
		{ID: "103-hahn-gold", Name: "Hahn Gold", Brewery: "Hahn Brewing Co", ABV: 3.5},
		{ID: "104-hahn-gold-cold-filtered", Name: "Hahn Gold Cold Filtered", Brewery: "Hahn Brewing Co", ABV: 3.5},
		{ID: "105-hahn-ice", Name: "Hahn Ice", Brewery: "Hahn Brewing Co", ABV: 4.9},
		{ID: "106-hahn-premium", Name: "Hahn Premium", Brewery: "Hahn Brewing Co", ABV: 5.0},
		{ID: "107-hahn-premium-light", Name: "Hahn Premium Light", Brewery: "Hahn Brewing Co", ABV: 2.7},
		{ID: "108-hat-lifter-stout", Name: "Hat Lifter Stout", Brewery: "Grand Ridge", ABV: 4.9},
		{ID: "109-heritage", Name: "Heritage", Brewery: "Cooper's", ABV: 5.2},
		{ID: "110-hightail-ale", Name: "Hightail Ale", Brewery: "Mountain Goat Beer", ABV: 4.5},
		{ID: "111-holgate-old-pale-ale", Name: "Holgate Old Pale Ale", Brewery: "Holgate Brewery", ABV: 5.0},
		{ID: "112-india-pale-ale", Name: "India Pale Ale", Brewery: "Malt Shovel Brewery", ABV: 5.6},
		{ID: "113-j.-boag's-original-bitter", Name: "J. Boag's Original Bitter", Brewery: "J. Boag & Son", ABV: 4.7},
		{ID: "114-jack-russell", Name: "Jack Russell", Brewery: "Cooper's", ABV: 4.9},
		{ID: "115-james-boag's-premium", Name: "James Boag's Premium", Brewery: "J. Boag & Son", ABV: 5.0},
		{ID: "116-james-squire-ipa", Name: "James Squire IPA", Brewery: "Malt Shovel Brewery", ABV: 5.6},
		{ID: "117-james-squire-original-amber-ale", Name: "James Squire Original Amber Ale", Brewery: "Malt Shovel Brewery", ABV: 5.0},
		{ID: "118-james-squire-original-pilsener", Name: "James Squire Original Pilsener", Brewery: "Malt Shovel Brewery", ABV: 5.0},
		{ID: "119-james-squire-porter", Name: "James Squire Porter", Brewery: "Malt Shovel Brewery", ABV: 5.0},
		{ID: "120-jarrah-jacks-wheat-beer", Name: "Jarrah Jacks Wheat Beer", Brewery: "Pemberton Brewing Co", ABV: 5.1},
		{ID: "121-kent-old-brown", Name: "Kent Old Brown", Brewery: "Carlton and United", ABV: 4.4},
		{ID: "122-king-premium-lager", Name: "King Premium Lager", Brewery: "n Brewing Company", ABV: 4.9},
		{ID: "123-light-bitter", Name: "Light Bitter", Brewery: "Carlton and United", ABV: 2.8},
		{ID: "124-live", Name: "Live", Brewery: "Little Creatures Brewing P/L", ABV: 5.2},
		{ID: "125-longbrew-lager", Name: "Longbrew Lager", Brewery: "Hahn Brewing", ABV: 4.5},
		{ID: "126-lugger-beer", Name: "Lugger Beer", Brewery: "Broome Brewery", ABV: 7.0},
		{ID: "127-malthouse-real-ale", Name: "Malthouse Real Ale", Brewery: "Matilda Bay", ABV: 5.8},
		{ID: "128-mariner-bitter", Name: "Mariner Bitter", Brewery: "Fremantle Brewery", ABV: 5.0},
		{ID: "129-matilda-bay-bitter", Name: "Matilda Bay Bitter", Brewery: "Matilda Bay", ABV: 3.5},
		{ID: "130-maxim", Name: "Maxim", Brewery: "Toohey's", ABV: 4.6},
		{ID: "131-melbourne-bitter", Name: "Melbourne Bitter", Brewery: "Carlton and United", ABV: 4.9},
		{ID: "132-mez", Name: "Mez", Brewery: "South Australian Brewing Co", ABV: 5.5},
		{ID: "133-midland-fettler", Name: "Midland Fettler", Brewery: "Inchant Brewing Co", ABV: 6.3},
		{ID: "134-millenium-ale-hahn-special-vintage", Name: "Millenium Ale Hahn Special Vintage", Brewery: "Hahn Brewing Co", ABV: 8.0},
		{ID: "135-moonlite-pure-malt-beer", Name: "Moonlite Pure Malt Beer", Brewery: "Grand Ridge", ABV: 3.3},
		{ID: "136-mountain-ale", Name: "Mountain Ale", Brewery: "Jamieson Brewery", ABV: 4.0},
		{ID: "137-mt-macedon-ale", Name: "Mt Macedon Ale", Brewery: "Holgate Brewery", ABV: 4.5},
		{ID: "138-natural-cellar", Name: "Natural Cellar", Brewery: "Palatinat", ABV: 4.1},
		{ID: "139-new---genuine-draught", Name: "New - Genuine Draught", Brewery: "Toohey's", ABV: 4.8},
		{ID: "140-new-light", Name: "New Light", Brewery: "Cooper's", ABV: 2.9},
		{ID: "141-octoberfest-palatinat", Name: "Octoberfest Palatinat", Brewery: "Palatinat", ABV: 4.5},
		{ID: "142-old-ale", Name: "Old Ale", Brewery: "Coonawarra Lawrence Vistor", ABV: 5.0},
		{ID: "143-palatinator-dark", Name: "Palatinator Dark", Brewery: "Palatinat", ABV: 4.1},
		{ID: "144-palatinator-original-may-bock", Name: "Palatinator Original May Bock", Brewery: "Palatinat", ABV: 6.0},
		{ID: "145-palatinus-golden-lager", Name: "Palatinus Golden Lager", Brewery: "Palatinat", ABV: 4.5},
		{ID: "146-palatinus-light-lager", Name: "Palatinus Light Lager", Brewery: "Palatinat", ABV: 3.0},
		{ID: "147-palatinatus-smoker-wheat-beer", Name: "Palatinatus Smoker Wheat Beer", Brewery: "Palatinat", ABV: 4.0},
		{ID: "148-pale-ale", Name: "Pale Ale", Brewery: "Geelong Brewing Co", ABV: 4.5},
		{ID: "149-pale-ale", Name: "Pale Ale", Brewery: "Mountain Goat Beer", ABV: 4.5},
		{ID: "150-pearl-lager", Name: "Pearl Lager", Brewery: "Broome Brewery", ABV: 3.4},
		{ID: "151-pi55-weak", Name: "Pi55 Weak", Brewery: "Pi55 Beer Co", ABV: 2.5},
		{ID: "152-pike's-oakbank-beer", Name: "Pike's Oakbank Beer", Brewery: "Pike's Oakbank Brewery", ABV: 4.9},
		{ID: "153-pils", Name: "Pils", Brewery: "Toohey's", ABV: 5.2},
		{ID: "154-piss", Name: "Piss", Brewery: "Piss Beer Co", ABV: 4.9},
		{ID: "155-power's-bitter", Name: "Power's Bitter", Brewery: "Queensland Breweries", ABV: 4.8},
		{ID: "156-power's-gold", Name: "Power's Gold", Brewery: "Queensland Breweries", ABV: 3.4},
		{ID: "157-power's-ice", Name: "Power's Ice", Brewery: "Queensland Breweries", ABV: 4.6},
		{ID: "158-power's-light", Name: "Power's Light", Brewery: "Queensland Breweries", ABV: 2.8},
		{ID: "159-premier-lager", Name: "Premier Lager", Brewery: "Matilda Bay", ABV: 3.4},
		{ID: "160-premium", Name: "Premium", Brewery: "Geelong Brewing Co", ABV: 4.9},
		{ID: "161-premium-dry", Name: "Premium Dry", Brewery: "Carlton and United", ABV: 5.0},
		{ID: "162-premium-lager", Name: "Premium Lager", Brewery: "Carlton and United", ABV: 3.4},
		{ID: "163-premium-light", Name: "Premium Light", Brewery: "Cascade", ABV: 2.9},
		{ID: "164-premium-light", Name: "Premium Light", Brewery: "J. Boag & Son", ABV: 2.9},
		{ID: "165-premium-pilsener-lager", Name: "Premium Pilsener Lager", Brewery: "Matilda Bay", ABV: 4.9},
		{ID: "166-pure-blonde", Name: "Pure Blonde", Brewery: "Carlton and United", ABV: 4.6},
		{ID: "167-real-bitter-ale", Name: "Real Bitter Ale", Brewery: "Reschs", ABV: 4.6},
		{ID: "168-red-ant", Name: "Red Ant", Brewery: "Jerningham St. Brewery", ABV: 4.5},
		{ID: "169-red-back-original", Name: "Red Back Original", Brewery: "Matilda Bay", ABV: 4.7},
		{ID: "170-red-bitter-beer", Name: "Red Bitter Beer", Brewery: "Toohey's", ABV: 5.0},
		{ID: "171-red-dog", Name: "Red Dog", Brewery: "Matilda Bay", ABV: 5.0},
		{ID: "172-redback-light", Name: "Redback Light", Brewery: "Matilda Bay", ABV: 3.4},
		{ID: "173-regency-light", Name: "Regency Light", Brewery: "Cooper's", ABV: 2.0},
		{ID: "174-reschs-pilsner", Name: "Reschs Pilsner", Brewery: "Reschs", ABV: 4.6},
		{ID: "175-rogers'", Name: "Rogers'", Brewery: "Little Creatures Brewing P/L", ABV: 3.8},
		{ID: "176-roof-top-real-lager", Name: "Roof Top Real Lager", Brewery: "Carlton and United", ABV: 4.7},
		{ID: "177-sanctuary-cove-premium-lager", Name: "Sanctuary Cove Premium Lager", Brewery: "Gold Coast Brewery", ABV: 4.9},
		{ID: "178-settler's-pale", Name: "Settler's Pale", Brewery: "Bootleg Brewery", ABV: 4.8},
		{ID: "179-sheaf-stout", Name: "Sheaf Stout", Brewery: "Carlton and United", ABV: 5.7},
		{ID: "180-southern-draught", Name: "Southern Draught", Brewery: "Cascade", ABV: 4.8},
		{ID: "181-southwark-bitter", Name: "Southwark Bitter", Brewery: "South Australian Brewing Co", ABV: 4.5},
		{ID: "182-southwark-black-ale", Name: "Southwark Black Ale", Brewery: "South Australian Brewing Co", ABV: 4.4},
		{ID: "183-southwark-old-stout", Name: "Southwark Old Stout", Brewery: "South Australian Brewing Co", ABV: 7.4},
		{ID: "184-southwark-premium-lager", Name: "Southwark Premium Lager", Brewery: "South Australian Brewering Co", ABV: 5.2},
		{ID: "185-southwark-white-beer", Name: "Southwark White Beer", Brewery: "South Australian Brewing Co", ABV: 5.0},
		{ID: "186-sovereign", Name: "Sovereign", Brewery: "Carlton and United", ABV: 2.5},
		{ID: "187-sovereign-superior-lager", Name: "Sovereign Superior Lager", Brewery: "Castlemaine Perkins", ABV: 3.8},
		{ID: "188-sparkling-xxx", Name: "Sparkling XXX", Brewery: "Castlemaine Perkins", ABV: 5.2},
		{ID: "189-special-stout", Name: "Special Stout", Brewery: "Cascade", ABV: 5.8},
		{ID: "190-st-george", Name: "St George", Brewery: "J. Boag & Son", ABV: 4.8},
		{ID: "191-stockade", Name: "Stockade", Brewery: "Stockade Brewery", ABV: 5.0},
		{ID: "192-summer-wheat-beer", Name: "Summer Wheat Beer", Brewery: "Malt Shovel Brewery", ABV: 5.0},
		{ID: "193-supershine", Name: "Supershine", Brewery: "Grand Ridge", ABV: 11.0},
		{ID: "194-surefoot-stout", Name: "Surefoot Stout", Brewery: "Mountain Goat Beer", ABV: 5.0},
		{ID: "195-swan-draught", Name: "Swan Draught", Brewery: "Swan Brewery", ABV: 4.8},
		{ID: "196-swan-gold", Name: "Swan Gold", Brewery: "Swan Brewery", ABV: 3.5},
		{ID: "197-swan-lager", Name: "Swan Lager", Brewery: "Swan Brewery", ABV: 4.9},
		{ID: "198-swan-light", Name: "Swan Light", Brewery: "Swan Brewery", ABV: 0.9},
		{ID: "199-swan-mid", Name: "Swan Mid", Brewery: "Swan Brewery", ABV: 3.5},
		{ID: "200-swan-stout", Name: "Swan Stout", Brewery: "Swan Brewery", ABV: 6.8},
		{ID: "201-sydney-bitter", Name: "Sydney Bitter", Brewery: "Toohey's", ABV: 4.9},
		{ID: "202-tasman-bitter", Name: "Tasman Bitter", Brewery: "Tasmanian Breweries", ABV: 4.8},
		{ID: "203-tasman-ice", Name: "Tasman Ice", Brewery: "Tasmanian Breweries", ABV: 4.9},
		{ID: "204-tasman-special-bitter", Name: "Tasman Special Bitter", Brewery: "Tasmanian Breweries", ABV: 2.8},
		{ID: "205-tenterfield-saddler-1870", Name: "Tenterfield Saddler 1870", Brewery: "Gold Coast Brewery", ABV: 4.9},
		{ID: "206-thomas-cooper's-finest-export-beer", Name: "Thomas Cooper's Finest Export Beer", Brewery: "Cooper's", ABV: 4.9},
		{ID: "207-thomas-jecks-commonwealth-ale", Name: "Thomas Jecks Commonwealth Ale", Brewery: "Inchant Brewing Co", ABV: 4.5},
		{ID: "208-tiger-head-bitter-beer", Name: "Tiger Head Bitter Beer", Brewery: "Cascade", ABV: 2.8},
		{ID: "209-tom's-brown", Name: "Tom's Brown", Brewery: "Bootleg Brewery", ABV: 4.0},
		{ID: "210-tomahawk", Name: "Tomahawk", Brewery: "Tomahawk", ABV: 4.9},
		{ID: "211-toohey's-christmas-brew", Name: "Toohey's Christmas Brew", Brewery: "Toohey's", ABV: 5.0},
		{ID: "212-toohey's-draught", Name: "Toohey's Draught", Brewery: "Toohey's", ABV: 4.6},
		{ID: "213-toohey's-extra-dry", Name: "Toohey's Extra Dry", Brewery: "Toohey's", ABV: 5.0},
		{ID: "214-toohey's-gold-bitter-beer", Name: "Toohey's Gold Bitter Beer", Brewery: "Toohey's", ABV: 3.4},
		{ID: "215-toohey's-old-black-ale", Name: "Toohey's Old Black Ale", Brewery: "Toohey's", ABV: 4.4},
		{ID: "216-vb-original-ale", Name: "VB Original Ale", Brewery: "Carlton and United", ABV: 4.6},
		{ID: "217-victoria-bitter", Name: "Victoria Bitter", Brewery: "Carlton and United", ABV: 4.9},
		{ID: "218-vienna-red", Name: "Vienna Red", Brewery: "Hahn Brewing Co", ABV: 5.0},
		{ID: "219-wa-gold", Name: "WA Gold", Brewery: "Carlton and United", ABV: 3.0},
		{ID: "220-west-end-draught", Name: "West End Draught", Brewery: "South Australian Brewering Co", ABV: 4.5},
		{ID: "221-west-end-gold", Name: "West End Gold", Brewery: "South Australian Brewing Co", ABV: 3.5},
		{ID: "222-west-end-light", Name: "West End Light", Brewery: "South Australian Brewing Co", ABV: 2.7},
		{ID: "223-white-lightning-dingo-bitter", Name: "White Lightning Dingo Bitter", Brewery: "Geelong Brewing Co", ABV: 4.9},
		{ID: "224-winter-ale", Name: "Winter Ale", Brewery: "Holgate Brewery", ABV: 6.0},
		{ID: "225-witbier", Name: "Witbier", Brewery: "Hahn Brewing Co", ABV: 5.0},
		{ID: "226-wodonga-wheat-beer", Name: "Wodonga Wheat Beer", Brewery: "Palatinat", ABV: 4.0},
		{ID: "227-xxxx-dl-lager", Name: "XXXX DL Lager", Brewery: "Castlemaine Perkins", ABV: 4.4},
		{ID: "228-xxxx-gold", Name: "XXXX Gold", Brewery: "Castlemaine Perkins", ABV: 3.5},
		{ID: "229-xxxx-light-bitter", Name: "XXXX Light Bitter", Brewery: "Castlemaine Perkins", ABV: 2.5},
		{ID: "230-xxxx-original-draught", Name: "XXXX Original Draught", Brewery: "Castlemaine Perkins", ABV: 4.8},
		{ID: "231-yarra-valley-gold", Name: "Yarra Valley Gold", Brewery: "Grand Ridge", ABV: 4.9},
		{ID: "232-premium-beer", Name: "Premium Beer", Brewery: "Sapporo Breweries", ABV: 5.0},
		{ID: "233-super-dry", Name: "Super Dry", Brewery: "Hahn Brewing Co", ABV: 4.6},
		{ID: "234-james-st.-premium-lager", Name: "James St. Premium Lager", Brewery: "Valley Hops Brewing", ABV: 4.9},
		{ID: "235-geezer-smooth-ale", Name: "Geezer Smooth Ale", Brewery: "Valley Hops Brewing", ABV: 4.1},
		{ID: "236-interloper-hazy-ipa", Name: "Interloper Hazy IPA", Brewery: "Valley Hops Brewing", ABV: 6.0},
		{ID: "237-diehards-mid-lager", Name: "Diehards Mid Lager", Brewery: "Valley Hops Brewing", ABV: 3.5},
		{ID: "238-diehards-original-lager", Name: "Diehards Original Lager", Brewery: "Valley Hops Brewing", ABV: 4.5},
		{ID: "239-21-pubs-pale-ale", Name: "21 Pubs Pale Ale", Brewery: "Valley Hops Brewing", ABV: 5.0},
		{ID: "240-exhibitionist-xpa", Name: "Exhibitionist XPA", Brewery: "Valley Hops Brewing", ABV: 4.2},
		{ID: "241-pabst-blue-ribbon", Name: "Pabst Blue Ribbon", Brewery: "Pabst Brewing Company", ABV: 4.7},
		{ID: "242-super-dry", Name: "Super Dry", Brewery: "Asahi Group", ABV: 5.0},
		{ID: "243-paradise-ipa", Name: "Paradise IPA", Brewery: "Felon's Brewing Co", ABV: 6.0},
		{ID: "244-paloma-sour", Name: "Paloma Sour", Brewery: "Felon's Brewing Co", ABV: 4.5},
		{ID: "245-mid-crush", Name: "Mid Crush", Brewery: "Felon's Brewing Co", ABV: 3.5},
		{ID: "246-ipa", Name: "IPA", Brewery: "Felon's Brewing Co", ABV: 6.2},
		{ID: "247-australian-pale-ale", Name: "Australian Pale Ale", Brewery: "Felon's Brewing Co", ABV: 5.0},
		{ID: "248-galaxy-haze", Name: "Galaxy Haze", Brewery: "Felon's Brewing Co", ABV: 4.4},
		{ID: "249-crisp-lager", Name: "Crisp Lager", Brewery: "Felon's Brewing Co", ABV: 4.2},
	}
	for _, b := range beers {
		item := CatalogueItem{
			PK:      "CATALOGUE",
			SK:      fmt.Sprintf("BEER#%s", b.ID),
			GSI1PK:  "CATALOGUE",
			GSI1SK:  fmt.Sprintf("%s#%s", b.Brewery, b.Name),
			BeerID:  b.ID,
			Name:    b.Name,
			Brewery: b.Brewery,
			ABV:     b.ABV,
		}

		av, _ := attributevalue.MarshalMap(item)
		_, err := db.PutItem(context.Background(), &dynamodb.PutItemInput{
			TableName: beerAws.TableName(),
			Item:      av,
		})
		if err != nil {
			log.Printf("Error inserting %s: %v", b.Name, err)
		}
	}
	log.Println("Seed complete!")
}
