/**
 * Pre-renders KaTeX formulas to static HTML at build time.
 * Run via: tsx scripts/prerender-latex.ts
 * Output: src/lib/latexPrerendered.ts
 *
 * This eliminates the KaTeX runtime (~500KB of JS + fonts) from the bundle.
 * The CSS is also inlined so no katex.min.css import is needed at runtime.
 */

import katex from "katex";
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const formulas: Record<string, { tex: string; display: boolean }> = {
  tbwFormula: {
    tex: String.raw`\text{TBW} = a + (b \times \text{Age}) + (c \times \text{Height}) + (d \times \text{Weight})`,
    display: true,
  },
  tbwFemale: {
    tex: String.raw`a = -2.097,\quad b = 0,\quad c = 0.1069,\quad d = 0.2466`,
    display: true,
  },
  tbwMale: {
    tex: String.raw`a = 2.447,\quad b = -0.09516,\quad c = 0.1074,\quad d = 0.3362`,
    display: true,
  },
  bacJump: {
    tex: String.raw`\text{BAC}_{\text{Jump}} = \frac{0.806 \times \text{std. drinks}}{\text{TBW}}`,
    display: true,
  },
  bacNow: {
    tex: String.raw`\text{BAC}_{\text{Now}} = \sum(\text{BAC}_{\text{Jump}}) - (0.015 \times \text{hours since first drink})`,
    display: true,
  },
};

const rendered: Record<string, string> = {};
for (const [key, { tex, display }] of Object.entries(formulas)) {
  rendered[key] = katex.renderToString(tex, {
    displayMode: display,
    throwOnError: false,
    output: "html",
  });
}

const output = `// AUTO-GENERATED by scripts/prerender-latex.ts — do not edit manually
// Re-run \`tsx scripts/prerender-latex.ts\` if formulas change.
export const LATEX = ${JSON.stringify(rendered, null, 2)} as const;
`;

const outPath = resolve(__dirname, "../src/lib/latexPrerendered.ts");
writeFileSync(outPath, output, "utf-8");
console.log(
  `✓ Pre-rendered ${Object.keys(rendered).length} formulas → src/lib/latexPrerendered.ts`,
);
